//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.20 at 02:18:37 PM CEST 
//


package org.submarine.client.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ParticipantBandKind.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ParticipantBandKind"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="top_initiating"/&gt;
 *     &lt;enumeration value="middle_initiating"/&gt;
 *     &lt;enumeration value="bottom_initiating"/&gt;
 *     &lt;enumeration value="top_non_initiating"/&gt;
 *     &lt;enumeration value="middle_non_initiating"/&gt;
 *     &lt;enumeration value="bottom_non_initiating"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */


public enum ParticipantBandKind {


    TOP_INITIATING("top_initiating"),

    MIDDLE_INITIATING("middle_initiating"),

    BOTTOM_INITIATING("bottom_initiating"),

    TOP_NON_INITIATING("top_non_initiating"),

    MIDDLE_NON_INITIATING("middle_non_initiating"),

    BOTTOM_NON_INITIATING("bottom_non_initiating");
    private final String value;

    ParticipantBandKind(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ParticipantBandKind fromValue(String v) {
        for (ParticipantBandKind c: ParticipantBandKind.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
