//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.20 at 02:18:37 PM CEST 
//


package org.submarine.client.model;



/**
 * <p>Java class for tAdHocSubProcess complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tAdHocSubProcess"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.omg.org/spec/BPMN/20100524/MODEL}tSubProcess"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="completionCondition" type="{http://www.omg.org/spec/BPMN/20100524/MODEL}tExpression" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="cancelRemainingInstances" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" /&gt;
 *       &lt;attribute name="ordering" type="{http://www.omg.org/spec/BPMN/20100524/MODEL}tAdHocOrdering" /&gt;
 *       &lt;anyAttribute processContents='lax' namespace='##other'/&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
public interface TAdHocSubProcess extends TSubProcess
{


    /**
     * Gets the value of the completionCondition property.
     * 
     * @return
     *     possible object is
     *     {@link TExpression }
     *     
     */
    TExpression getCompletionCondition();

    /**
     * Sets the value of the completionCondition property.
     * 
     * @param value
     *     allowed object is
     *     {@link TExpression }
     *     
     */
    void setCompletionCondition(TExpression value);

    /**
     * Gets the value of the cancelRemainingInstances property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    boolean isCancelRemainingInstances();

    /**
     * Sets the value of the cancelRemainingInstances property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    void setCancelRemainingInstances(Boolean value);

    /**
     * Gets the value of the ordering property.
     * 
     * @return
     *     possible object is
     *     {@link TAdHocOrdering }
     *     
     */
    TAdHocOrdering getOrdering();

    /**
     * Sets the value of the ordering property.
     * 
     * @param value
     *     allowed object is
     *     {@link TAdHocOrdering }
     *     
     */
    void setOrdering(TAdHocOrdering value);

}
