//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.06 at 05:11:55 PM BRT 
//


package org.submarine.client.bpmn;

import javax.annotation.Generated;

@Generated("Generated by jaxb-visitor")
public class BaseVisitor<R, E extends Throwable >
    implements Visitor<R, E>
{


    @Override
    public R visit(BPMNDiagram aBean)
        throws E
    {
        return null;
    }

    @Override
    public R visit(BPMNEdge aBean)
        throws E
    {
        return null;
    }

    @Override
    public R visit(BPMNLabel aBean)
        throws E
    {
        return null;
    }

    @Override
    public R visit(BPMNLabelStyle aBean)
        throws E
    {
        return null;
    }

    @Override
    public R visit(BPMNPlane aBean)
        throws E
    {
        return null;
    }

    @Override
    public R visit(BPMNShape aBean)
        throws E
    {
        return null;
    }

    @Override
    public R visit(Bounds aBean)
        throws E
    {
        return null;
    }

    @Override
    public R visit(org.submarine.client.bpmn.DiagramElement.Extension aBean)
        throws E
    {
        return null;
    }

    @Override
    public R visit(Font aBean)
        throws E
    {
        return null;
    }

    @Override
    public R visit(Point aBean)
        throws E
    {
        return null;
    }

    @Override
    public R visit(TAdHocSubProcess aBean)
        throws E
    {
        return null;
    }

    @Override
    public R visit(TAssignment aBean)
        throws E
    {
        return null;
    }

    @Override
    public R visit(TAssociation aBean)
        throws E
    {
        return null;
    }

    @Override
    public R visit(TAuditing aBean)
        throws E
    {
        return null;
    }

    @Override
    public R visit(TBoundaryEvent aBean)
        throws E
    {
        return null;
    }

    @Override
    public R visit(TBusinessRuleTask aBean)
        throws E
    {
        return null;
    }

    @Override
    public R visit(TCallActivity aBean)
        throws E
    {
        return null;
    }

    @Override
    public R visit(TCallChoreography aBean)
        throws E
    {
        return null;
    }

    @Override
    public R visit(TCallConversation aBean)
        throws E
    {
        return null;
    }

    @Override
    public R visit(TCallableElement aBean)
        throws E
    {
        return null;
    }

    @Override
    public R visit(TCancelEventDefinition aBean)
        throws E
    {
        return null;
    }

    @Override
    public R visit(TCategory aBean)
        throws E
    {
        return null;
    }

    @Override
    public R visit(TCategoryValue aBean)
        throws E
    {
        return null;
    }

    @Override
    public R visit(TChoreography aBean)
        throws E
    {
        return null;
    }

    @Override
    public R visit(TChoreographyTask aBean)
        throws E
    {
        return null;
    }

    @Override
    public R visit(TCollaboration aBean)
        throws E
    {
        return null;
    }

    @Override
    public R visit(TCompensateEventDefinition aBean)
        throws E
    {
        return null;
    }

    @Override
    public R visit(TComplexBehaviorDefinition aBean)
        throws E
    {
        return null;
    }

    @Override
    public R visit(TComplexGateway aBean)
        throws E
    {
        return null;
    }

    @Override
    public R visit(TConditionalEventDefinition aBean)
        throws E
    {
        return null;
    }

    @Override
    public R visit(TConversation aBean)
        throws E
    {
        return null;
    }

    @Override
    public R visit(TConversationAssociation aBean)
        throws E
    {
        return null;
    }

    @Override
    public R visit(TConversationLink aBean)
        throws E
    {
        return null;
    }

    @Override
    public R visit(TCorrelationKey aBean)
        throws E
    {
        return null;
    }

    @Override
    public R visit(TCorrelationProperty aBean)
        throws E
    {
        return null;
    }

    @Override
    public R visit(TCorrelationPropertyBinding aBean)
        throws E
    {
        return null;
    }

    @Override
    public R visit(TCorrelationPropertyRetrievalExpression aBean)
        throws E
    {
        return null;
    }

    @Override
    public R visit(TCorrelationSubscription aBean)
        throws E
    {
        return null;
    }

    @Override
    public R visit(TDataAssociation aBean)
        throws E
    {
        return null;
    }

    @Override
    public R visit(TDataInput aBean)
        throws E
    {
        return null;
    }

    @Override
    public R visit(TDataInputAssociation aBean)
        throws E
    {
        return null;
    }

    @Override
    public R visit(TDataObject aBean)
        throws E
    {
        return null;
    }

    @Override
    public R visit(TDataObjectReference aBean)
        throws E
    {
        return null;
    }

    @Override
    public R visit(TDataOutput aBean)
        throws E
    {
        return null;
    }

    @Override
    public R visit(TDataOutputAssociation aBean)
        throws E
    {
        return null;
    }

    @Override
    public R visit(TDataState aBean)
        throws E
    {
        return null;
    }

    @Override
    public R visit(TDataStore aBean)
        throws E
    {
        return null;
    }

    @Override
    public R visit(TDataStoreReference aBean)
        throws E
    {
        return null;
    }

    @Override
    public R visit(TDefinitions aBean)
        throws E
    {
        return null;
    }

    @Override
    public R visit(TDocumentation aBean)
        throws E
    {
        return null;
    }

    @Override
    public R visit(TEndEvent aBean)
        throws E
    {
        return null;
    }

    @Override
    public R visit(TEndPoint aBean)
        throws E
    {
        return null;
    }

    @Override
    public R visit(TError aBean)
        throws E
    {
        return null;
    }

    @Override
    public R visit(TErrorEventDefinition aBean)
        throws E
    {
        return null;
    }

    @Override
    public R visit(TEscalation aBean)
        throws E
    {
        return null;
    }

    @Override
    public R visit(TEscalationEventDefinition aBean)
        throws E
    {
        return null;
    }

    @Override
    public R visit(TEventBasedGateway aBean)
        throws E
    {
        return null;
    }

    @Override
    public R visit(TExclusiveGateway aBean)
        throws E
    {
        return null;
    }

    @Override
    public R visit(TExpression aBean)
        throws E
    {
        return null;
    }

    @Override
    public R visit(TExtension aBean)
        throws E
    {
        return null;
    }

    @Override
    public R visit(TExtensionElements aBean)
        throws E
    {
        return null;
    }

    @Override
    public R visit(TFormalExpression aBean)
        throws E
    {
        return null;
    }

    @Override
    public R visit(TGateway aBean)
        throws E
    {
        return null;
    }

    @Override
    public R visit(TGlobalBusinessRuleTask aBean)
        throws E
    {
        return null;
    }

    @Override
    public R visit(TGlobalChoreographyTask aBean)
        throws E
    {
        return null;
    }

    @Override
    public R visit(TGlobalConversation aBean)
        throws E
    {
        return null;
    }

    @Override
    public R visit(TGlobalManualTask aBean)
        throws E
    {
        return null;
    }

    @Override
    public R visit(TGlobalScriptTask aBean)
        throws E
    {
        return null;
    }

    @Override
    public R visit(TGlobalTask aBean)
        throws E
    {
        return null;
    }

    @Override
    public R visit(TGlobalUserTask aBean)
        throws E
    {
        return null;
    }

    @Override
    public R visit(TGroup aBean)
        throws E
    {
        return null;
    }

    @Override
    public R visit(THumanPerformer aBean)
        throws E
    {
        return null;
    }

    @Override
    public R visit(TImplicitThrowEvent aBean)
        throws E
    {
        return null;
    }

    @Override
    public R visit(TImport aBean)
        throws E
    {
        return null;
    }

    @Override
    public R visit(TInclusiveGateway aBean)
        throws E
    {
        return null;
    }

    @Override
    public R visit(TInputOutputBinding aBean)
        throws E
    {
        return null;
    }

    @Override
    public R visit(TInputOutputSpecification aBean)
        throws E
    {
        return null;
    }

    @Override
    public R visit(TInputSet aBean)
        throws E
    {
        return null;
    }

    @Override
    public R visit(TInterface aBean)
        throws E
    {
        return null;
    }

    @Override
    public R visit(TIntermediateCatchEvent aBean)
        throws E
    {
        return null;
    }

    @Override
    public R visit(TIntermediateThrowEvent aBean)
        throws E
    {
        return null;
    }

    @Override
    public R visit(TItemDefinition aBean)
        throws E
    {
        return null;
    }

    @Override
    public R visit(TLane aBean)
        throws E
    {
        return null;
    }

    @Override
    public R visit(TLaneSet aBean)
        throws E
    {
        return null;
    }

    @Override
    public R visit(TLinkEventDefinition aBean)
        throws E
    {
        return null;
    }

    @Override
    public R visit(TManualTask aBean)
        throws E
    {
        return null;
    }

    @Override
    public R visit(TMessage aBean)
        throws E
    {
        return null;
    }

    @Override
    public R visit(TMessageEventDefinition aBean)
        throws E
    {
        return null;
    }

    @Override
    public R visit(TMessageFlow aBean)
        throws E
    {
        return null;
    }

    @Override
    public R visit(TMessageFlowAssociation aBean)
        throws E
    {
        return null;
    }

    @Override
    public R visit(TMonitoring aBean)
        throws E
    {
        return null;
    }

    @Override
    public R visit(TMultiInstanceLoopCharacteristics aBean)
        throws E
    {
        return null;
    }

    @Override
    public R visit(TOperation aBean)
        throws E
    {
        return null;
    }

    @Override
    public R visit(TOutputSet aBean)
        throws E
    {
        return null;
    }

    @Override
    public R visit(TParallelGateway aBean)
        throws E
    {
        return null;
    }

    @Override
    public R visit(TParticipant aBean)
        throws E
    {
        return null;
    }

    @Override
    public R visit(TParticipantAssociation aBean)
        throws E
    {
        return null;
    }

    @Override
    public R visit(TParticipantMultiplicity aBean)
        throws E
    {
        return null;
    }

    @Override
    public R visit(TPartnerEntity aBean)
        throws E
    {
        return null;
    }

    @Override
    public R visit(TPartnerRole aBean)
        throws E
    {
        return null;
    }

    @Override
    public R visit(TPerformer aBean)
        throws E
    {
        return null;
    }

    @Override
    public R visit(TPotentialOwner aBean)
        throws E
    {
        return null;
    }

    @Override
    public R visit(TProcess aBean)
        throws E
    {
        return null;
    }

    @Override
    public R visit(TProperty aBean)
        throws E
    {
        return null;
    }

    @Override
    public R visit(TReceiveTask aBean)
        throws E
    {
        return null;
    }

    @Override
    public R visit(TRelationship aBean)
        throws E
    {
        return null;
    }

    @Override
    public R visit(TRendering aBean)
        throws E
    {
        return null;
    }

    @Override
    public R visit(TResource aBean)
        throws E
    {
        return null;
    }

    @Override
    public R visit(TResourceAssignmentExpression aBean)
        throws E
    {
        return null;
    }

    @Override
    public R visit(TResourceParameter aBean)
        throws E
    {
        return null;
    }

    @Override
    public R visit(TResourceParameterBinding aBean)
        throws E
    {
        return null;
    }

    @Override
    public R visit(TResourceRole aBean)
        throws E
    {
        return null;
    }

    @Override
    public R visit(TScript aBean)
        throws E
    {
        return null;
    }

    @Override
    public R visit(TScriptTask aBean)
        throws E
    {
        return null;
    }

    @Override
    public R visit(TSendTask aBean)
        throws E
    {
        return null;
    }

    @Override
    public R visit(TSequenceFlow aBean)
        throws E
    {
        return null;
    }

    @Override
    public R visit(TServiceTask aBean)
        throws E
    {
        return null;
    }

    @Override
    public R visit(TSignal aBean)
        throws E
    {
        return null;
    }

    @Override
    public R visit(TSignalEventDefinition aBean)
        throws E
    {
        return null;
    }

    @Override
    public R visit(TStandardLoopCharacteristics aBean)
        throws E
    {
        return null;
    }

    @Override
    public R visit(TStartEvent aBean)
        throws E
    {
        return null;
    }

    @Override
    public R visit(TSubChoreography aBean)
        throws E
    {
        return null;
    }

    @Override
    public R visit(TSubConversation aBean)
        throws E
    {
        return null;
    }

    @Override
    public R visit(TSubProcess aBean)
        throws E
    {
        return null;
    }

    @Override
    public R visit(TTask aBean)
        throws E
    {
        return null;
    }

    @Override
    public R visit(TTerminateEventDefinition aBean)
        throws E
    {
        return null;
    }

    @Override
    public R visit(TText aBean)
        throws E
    {
        return null;
    }

    @Override
    public R visit(TTextAnnotation aBean)
        throws E
    {
        return null;
    }

    @Override
    public R visit(TTimerEventDefinition aBean)
        throws E
    {
        return null;
    }

    @Override
    public R visit(TTransaction aBean)
        throws E
    {
        return null;
    }

    @Override
    public R visit(TUserTask aBean)
        throws E
    {
        return null;
    }

}
