//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.06 at 05:11:55 PM BRT 
//


package org.submarine.client.bpmn;

import java.io.Serializable;
import javax.annotation.Generated;
import javax.xml.bind.JAXBElement;

@Generated("Generated by jaxb-visitor")
public class DepthFirstTraverserImpl<E extends Throwable >
    implements Traverser<E>
{


    @Override
    public void traverse(BPMNDiagram aBean, Visitor<?, E> aVisitor)
        throws E
    {
        if (aBean.getBPMNPlane()!= null) {
            aBean.getBPMNPlane().accept(aVisitor);
        }
        for (BPMNLabelStyle bean: aBean.getBPMNLabelStyle()) {
            bean.accept(aVisitor);
        }
    }

    @Override
    public void traverse(BPMNEdge aBean, Visitor<?, E> aVisitor)
        throws E
    {
        if (aBean.getBPMNLabel()!= null) {
            aBean.getBPMNLabel().accept(aVisitor);
        }
        for (Point bean: aBean.getWaypoint()) {
            bean.accept(aVisitor);
        }
        if (aBean.getExtension()!= null) {
            aBean.getExtension().accept(aVisitor);
        }
    }

    @Override
    public void traverse(BPMNLabel aBean, Visitor<?, E> aVisitor)
        throws E
    {
        if (aBean.getBounds()!= null) {
            aBean.getBounds().accept(aVisitor);
        }
        if (aBean.getExtension()!= null) {
            aBean.getExtension().accept(aVisitor);
        }
    }

    @Override
    public void traverse(BPMNLabelStyle aBean, Visitor<?, E> aVisitor)
        throws E
    {
        if (aBean.getFont()!= null) {
            aBean.getFont().accept(aVisitor);
        }
    }

    @Override
    public void traverse(BPMNPlane aBean, Visitor<?, E> aVisitor)
        throws E
    {
        for (JAXBElement<? extends DiagramElement> obj: aBean.getDiagramElement()) {
            if (obj.getValue()!= null) {
                obj.getValue().accept(aVisitor);
            }
        }
        if (aBean.getExtension()!= null) {
            aBean.getExtension().accept(aVisitor);
        }
    }

    @Override
    public void traverse(BPMNShape aBean, Visitor<?, E> aVisitor)
        throws E
    {
        if (aBean.getBPMNLabel()!= null) {
            aBean.getBPMNLabel().accept(aVisitor);
        }
        if (aBean.getBounds()!= null) {
            aBean.getBounds().accept(aVisitor);
        }
        if (aBean.getExtension()!= null) {
            aBean.getExtension().accept(aVisitor);
        }
    }

    @Override
    public void traverse(Bounds aBean, Visitor<?, E> aVisitor)
        throws E
    {
    }

    @Override
    public void traverse(DiagramElement.Extension aBean, Visitor<?, E> aVisitor)
        throws E
    {
        for (Object bean: aBean.getAny()) {
            if (bean instanceof Visitable) {
                ((Visitable) bean).accept(aVisitor);
            } else {
                if (bean instanceof JAXBElement<?> ) {
                    if (((JAXBElement<?> ) bean).getValue() instanceof Visitable) {
                        ((Visitable)((JAXBElement<?> ) bean).getValue()).accept(aVisitor);
                    }
                }
            }
        }
    }

    @Override
    public void traverse(Font aBean, Visitor<?, E> aVisitor)
        throws E
    {
    }

    @Override
    public void traverse(Point aBean, Visitor<?, E> aVisitor)
        throws E
    {
    }

    @Override
    public void traverse(TAdHocSubProcess aBean, Visitor<?, E> aVisitor)
        throws E
    {
        if (aBean.getCompletionCondition()!= null) {
            aBean.getCompletionCondition().accept(aVisitor);
        }
        for (TLaneSet bean: aBean.getLaneSet()) {
            bean.accept(aVisitor);
        }
        for (JAXBElement<? extends TFlowElement> obj: aBean.getFlowElement()) {
            if (obj.getValue()!= null) {
                obj.getValue().accept(aVisitor);
            }
        }
        for (JAXBElement<? extends TArtifact> obj: aBean.getArtifact()) {
            if (obj.getValue()!= null) {
                obj.getValue().accept(aVisitor);
            }
        }
        if (aBean.getIoSpecification()!= null) {
            aBean.getIoSpecification().accept(aVisitor);
        }
        for (TProperty bean: aBean.getProperty()) {
            bean.accept(aVisitor);
        }
        for (TDataInputAssociation bean: aBean.getDataInputAssociation()) {
            bean.accept(aVisitor);
        }
        for (TDataOutputAssociation bean: aBean.getDataOutputAssociation()) {
            bean.accept(aVisitor);
        }
        for (JAXBElement<? extends TResourceRole> obj: aBean.getResourceRole()) {
            if (obj.getValue()!= null) {
                obj.getValue().accept(aVisitor);
            }
        }
        if (aBean.getLoopCharacteristics()!= null) {
            aBean.getLoopCharacteristics().getValue().accept(aVisitor);
        }
        if (aBean.getDefault() instanceof Visitable) {
            ((Visitable) aBean.getDefault()).accept(aVisitor);
        }
        if (aBean.getAuditing()!= null) {
            aBean.getAuditing().accept(aVisitor);
        }
        if (aBean.getMonitoring()!= null) {
            aBean.getMonitoring().accept(aVisitor);
        }
        for (TDocumentation bean: aBean.getDocumentation()) {
            bean.accept(aVisitor);
        }
        if (aBean.getExtensionElements()!= null) {
            aBean.getExtensionElements().accept(aVisitor);
        }
    }

    @Override
    public void traverse(TAssignment aBean, Visitor<?, E> aVisitor)
        throws E
    {
        if (aBean.getFrom()!= null) {
            aBean.getFrom().accept(aVisitor);
        }
        if (aBean.getTo()!= null) {
            aBean.getTo().accept(aVisitor);
        }
        for (TDocumentation bean: aBean.getDocumentation()) {
            bean.accept(aVisitor);
        }
        if (aBean.getExtensionElements()!= null) {
            aBean.getExtensionElements().accept(aVisitor);
        }
    }

    @Override
    public void traverse(TAssociation aBean, Visitor<?, E> aVisitor)
        throws E
    {
        for (TDocumentation bean: aBean.getDocumentation()) {
            bean.accept(aVisitor);
        }
        if (aBean.getExtensionElements()!= null) {
            aBean.getExtensionElements().accept(aVisitor);
        }
    }

    @Override
    public void traverse(TAuditing aBean, Visitor<?, E> aVisitor)
        throws E
    {
        for (TDocumentation bean: aBean.getDocumentation()) {
            bean.accept(aVisitor);
        }
        if (aBean.getExtensionElements()!= null) {
            aBean.getExtensionElements().accept(aVisitor);
        }
    }

    @Override
    public void traverse(TBoundaryEvent aBean, Visitor<?, E> aVisitor)
        throws E
    {
        for (TDataOutput bean: aBean.getDataOutput()) {
            bean.accept(aVisitor);
        }
        for (TDataOutputAssociation bean: aBean.getDataOutputAssociation()) {
            bean.accept(aVisitor);
        }
        if (aBean.getOutputSet()!= null) {
            aBean.getOutputSet().accept(aVisitor);
        }
        for (JAXBElement<? extends TEventDefinition> obj: aBean.getEventDefinition()) {
            if (obj.getValue()!= null) {
                obj.getValue().accept(aVisitor);
            }
        }
        for (TProperty bean: aBean.getProperty()) {
            bean.accept(aVisitor);
        }
        if (aBean.getAuditing()!= null) {
            aBean.getAuditing().accept(aVisitor);
        }
        if (aBean.getMonitoring()!= null) {
            aBean.getMonitoring().accept(aVisitor);
        }
        for (TDocumentation bean: aBean.getDocumentation()) {
            bean.accept(aVisitor);
        }
        if (aBean.getExtensionElements()!= null) {
            aBean.getExtensionElements().accept(aVisitor);
        }
    }

    @Override
    public void traverse(TBusinessRuleTask aBean, Visitor<?, E> aVisitor)
        throws E
    {
        if (aBean.getIoSpecification()!= null) {
            aBean.getIoSpecification().accept(aVisitor);
        }
        for (TProperty bean: aBean.getProperty()) {
            bean.accept(aVisitor);
        }
        for (TDataInputAssociation bean: aBean.getDataInputAssociation()) {
            bean.accept(aVisitor);
        }
        for (TDataOutputAssociation bean: aBean.getDataOutputAssociation()) {
            bean.accept(aVisitor);
        }
        for (JAXBElement<? extends TResourceRole> obj: aBean.getResourceRole()) {
            if (obj.getValue()!= null) {
                obj.getValue().accept(aVisitor);
            }
        }
        if (aBean.getLoopCharacteristics()!= null) {
            aBean.getLoopCharacteristics().getValue().accept(aVisitor);
        }
        if (aBean.getDefault() instanceof Visitable) {
            ((Visitable) aBean.getDefault()).accept(aVisitor);
        }
        if (aBean.getAuditing()!= null) {
            aBean.getAuditing().accept(aVisitor);
        }
        if (aBean.getMonitoring()!= null) {
            aBean.getMonitoring().accept(aVisitor);
        }
        for (TDocumentation bean: aBean.getDocumentation()) {
            bean.accept(aVisitor);
        }
        if (aBean.getExtensionElements()!= null) {
            aBean.getExtensionElements().accept(aVisitor);
        }
    }

    @Override
    public void traverse(TCallActivity aBean, Visitor<?, E> aVisitor)
        throws E
    {
        if (aBean.getIoSpecification()!= null) {
            aBean.getIoSpecification().accept(aVisitor);
        }
        for (TProperty bean: aBean.getProperty()) {
            bean.accept(aVisitor);
        }
        for (TDataInputAssociation bean: aBean.getDataInputAssociation()) {
            bean.accept(aVisitor);
        }
        for (TDataOutputAssociation bean: aBean.getDataOutputAssociation()) {
            bean.accept(aVisitor);
        }
        for (JAXBElement<? extends TResourceRole> obj: aBean.getResourceRole()) {
            if (obj.getValue()!= null) {
                obj.getValue().accept(aVisitor);
            }
        }
        if (aBean.getLoopCharacteristics()!= null) {
            aBean.getLoopCharacteristics().getValue().accept(aVisitor);
        }
        if (aBean.getDefault() instanceof Visitable) {
            ((Visitable) aBean.getDefault()).accept(aVisitor);
        }
        if (aBean.getAuditing()!= null) {
            aBean.getAuditing().accept(aVisitor);
        }
        if (aBean.getMonitoring()!= null) {
            aBean.getMonitoring().accept(aVisitor);
        }
        for (TDocumentation bean: aBean.getDocumentation()) {
            bean.accept(aVisitor);
        }
        if (aBean.getExtensionElements()!= null) {
            aBean.getExtensionElements().accept(aVisitor);
        }
    }

    @Override
    public void traverse(TCallChoreography aBean, Visitor<?, E> aVisitor)
        throws E
    {
        for (TParticipantAssociation bean: aBean.getParticipantAssociation()) {
            bean.accept(aVisitor);
        }
        for (TCorrelationKey bean: aBean.getCorrelationKey()) {
            bean.accept(aVisitor);
        }
        if (aBean.getAuditing()!= null) {
            aBean.getAuditing().accept(aVisitor);
        }
        if (aBean.getMonitoring()!= null) {
            aBean.getMonitoring().accept(aVisitor);
        }
        for (TDocumentation bean: aBean.getDocumentation()) {
            bean.accept(aVisitor);
        }
        if (aBean.getExtensionElements()!= null) {
            aBean.getExtensionElements().accept(aVisitor);
        }
    }

    @Override
    public void traverse(TCallConversation aBean, Visitor<?, E> aVisitor)
        throws E
    {
        for (TParticipantAssociation bean: aBean.getParticipantAssociation()) {
            bean.accept(aVisitor);
        }
        for (TCorrelationKey bean: aBean.getCorrelationKey()) {
            bean.accept(aVisitor);
        }
        for (TDocumentation bean: aBean.getDocumentation()) {
            bean.accept(aVisitor);
        }
        if (aBean.getExtensionElements()!= null) {
            aBean.getExtensionElements().accept(aVisitor);
        }
    }

    @Override
    public void traverse(TCallableElement aBean, Visitor<?, E> aVisitor)
        throws E
    {
        if (aBean.getIoSpecification()!= null) {
            aBean.getIoSpecification().accept(aVisitor);
        }
        for (TInputOutputBinding bean: aBean.getIoBinding()) {
            bean.accept(aVisitor);
        }
        for (TDocumentation bean: aBean.getDocumentation()) {
            bean.accept(aVisitor);
        }
        if (aBean.getExtensionElements()!= null) {
            aBean.getExtensionElements().accept(aVisitor);
        }
    }

    @Override
    public void traverse(TCancelEventDefinition aBean, Visitor<?, E> aVisitor)
        throws E
    {
        for (TDocumentation bean: aBean.getDocumentation()) {
            bean.accept(aVisitor);
        }
        if (aBean.getExtensionElements()!= null) {
            aBean.getExtensionElements().accept(aVisitor);
        }
    }

    @Override
    public void traverse(TCategory aBean, Visitor<?, E> aVisitor)
        throws E
    {
        for (TCategoryValue bean: aBean.getCategoryValue()) {
            bean.accept(aVisitor);
        }
        for (TDocumentation bean: aBean.getDocumentation()) {
            bean.accept(aVisitor);
        }
        if (aBean.getExtensionElements()!= null) {
            aBean.getExtensionElements().accept(aVisitor);
        }
    }

    @Override
    public void traverse(TCategoryValue aBean, Visitor<?, E> aVisitor)
        throws E
    {
        for (TDocumentation bean: aBean.getDocumentation()) {
            bean.accept(aVisitor);
        }
        if (aBean.getExtensionElements()!= null) {
            aBean.getExtensionElements().accept(aVisitor);
        }
    }

    @Override
    public void traverse(TChoreography aBean, Visitor<?, E> aVisitor)
        throws E
    {
        for (JAXBElement<? extends TFlowElement> obj: aBean.getFlowElement()) {
            if (obj.getValue()!= null) {
                obj.getValue().accept(aVisitor);
            }
        }
        for (TParticipant bean: aBean.getParticipant()) {
            bean.accept(aVisitor);
        }
        for (TMessageFlow bean: aBean.getMessageFlow()) {
            bean.accept(aVisitor);
        }
        for (JAXBElement<? extends TArtifact> obj: aBean.getArtifact()) {
            if (obj.getValue()!= null) {
                obj.getValue().accept(aVisitor);
            }
        }
        for (JAXBElement<? extends TConversationNode> obj: aBean.getConversationNode()) {
            if (obj.getValue()!= null) {
                obj.getValue().accept(aVisitor);
            }
        }
        for (TConversationAssociation bean: aBean.getConversationAssociation()) {
            bean.accept(aVisitor);
        }
        for (TParticipantAssociation bean: aBean.getParticipantAssociation()) {
            bean.accept(aVisitor);
        }
        for (TMessageFlowAssociation bean: aBean.getMessageFlowAssociation()) {
            bean.accept(aVisitor);
        }
        for (TCorrelationKey bean: aBean.getCorrelationKey()) {
            bean.accept(aVisitor);
        }
        for (TConversationLink bean: aBean.getConversationLink()) {
            bean.accept(aVisitor);
        }
        for (TDocumentation bean: aBean.getDocumentation()) {
            bean.accept(aVisitor);
        }
        if (aBean.getExtensionElements()!= null) {
            aBean.getExtensionElements().accept(aVisitor);
        }
    }

    @Override
    public void traverse(TChoreographyTask aBean, Visitor<?, E> aVisitor)
        throws E
    {
        for (TCorrelationKey bean: aBean.getCorrelationKey()) {
            bean.accept(aVisitor);
        }
        if (aBean.getAuditing()!= null) {
            aBean.getAuditing().accept(aVisitor);
        }
        if (aBean.getMonitoring()!= null) {
            aBean.getMonitoring().accept(aVisitor);
        }
        for (TDocumentation bean: aBean.getDocumentation()) {
            bean.accept(aVisitor);
        }
        if (aBean.getExtensionElements()!= null) {
            aBean.getExtensionElements().accept(aVisitor);
        }
    }

    @Override
    public void traverse(TCollaboration aBean, Visitor<?, E> aVisitor)
        throws E
    {
        for (TParticipant bean: aBean.getParticipant()) {
            bean.accept(aVisitor);
        }
        for (TMessageFlow bean: aBean.getMessageFlow()) {
            bean.accept(aVisitor);
        }
        for (JAXBElement<? extends TArtifact> obj: aBean.getArtifact()) {
            if (obj.getValue()!= null) {
                obj.getValue().accept(aVisitor);
            }
        }
        for (JAXBElement<? extends TConversationNode> obj: aBean.getConversationNode()) {
            if (obj.getValue()!= null) {
                obj.getValue().accept(aVisitor);
            }
        }
        for (TConversationAssociation bean: aBean.getConversationAssociation()) {
            bean.accept(aVisitor);
        }
        for (TParticipantAssociation bean: aBean.getParticipantAssociation()) {
            bean.accept(aVisitor);
        }
        for (TMessageFlowAssociation bean: aBean.getMessageFlowAssociation()) {
            bean.accept(aVisitor);
        }
        for (TCorrelationKey bean: aBean.getCorrelationKey()) {
            bean.accept(aVisitor);
        }
        for (TConversationLink bean: aBean.getConversationLink()) {
            bean.accept(aVisitor);
        }
        for (TDocumentation bean: aBean.getDocumentation()) {
            bean.accept(aVisitor);
        }
        if (aBean.getExtensionElements()!= null) {
            aBean.getExtensionElements().accept(aVisitor);
        }
    }

    @Override
    public void traverse(TCompensateEventDefinition aBean, Visitor<?, E> aVisitor)
        throws E
    {
        for (TDocumentation bean: aBean.getDocumentation()) {
            bean.accept(aVisitor);
        }
        if (aBean.getExtensionElements()!= null) {
            aBean.getExtensionElements().accept(aVisitor);
        }
    }

    @Override
    public void traverse(TComplexBehaviorDefinition aBean, Visitor<?, E> aVisitor)
        throws E
    {
        if (aBean.getCondition()!= null) {
            aBean.getCondition().accept(aVisitor);
        }
        if (aBean.getEvent()!= null) {
            aBean.getEvent().accept(aVisitor);
        }
        for (TDocumentation bean: aBean.getDocumentation()) {
            bean.accept(aVisitor);
        }
        if (aBean.getExtensionElements()!= null) {
            aBean.getExtensionElements().accept(aVisitor);
        }
    }

    @Override
    public void traverse(TComplexGateway aBean, Visitor<?, E> aVisitor)
        throws E
    {
        if (aBean.getActivationCondition()!= null) {
            aBean.getActivationCondition().accept(aVisitor);
        }
        if (aBean.getDefault() instanceof Visitable) {
            ((Visitable) aBean.getDefault()).accept(aVisitor);
        }
        if (aBean.getAuditing()!= null) {
            aBean.getAuditing().accept(aVisitor);
        }
        if (aBean.getMonitoring()!= null) {
            aBean.getMonitoring().accept(aVisitor);
        }
        for (TDocumentation bean: aBean.getDocumentation()) {
            bean.accept(aVisitor);
        }
        if (aBean.getExtensionElements()!= null) {
            aBean.getExtensionElements().accept(aVisitor);
        }
    }

    @Override
    public void traverse(TConditionalEventDefinition aBean, Visitor<?, E> aVisitor)
        throws E
    {
        if (aBean.getCondition()!= null) {
            aBean.getCondition().accept(aVisitor);
        }
        for (TDocumentation bean: aBean.getDocumentation()) {
            bean.accept(aVisitor);
        }
        if (aBean.getExtensionElements()!= null) {
            aBean.getExtensionElements().accept(aVisitor);
        }
    }

    @Override
    public void traverse(TConversation aBean, Visitor<?, E> aVisitor)
        throws E
    {
        for (TCorrelationKey bean: aBean.getCorrelationKey()) {
            bean.accept(aVisitor);
        }
        for (TDocumentation bean: aBean.getDocumentation()) {
            bean.accept(aVisitor);
        }
        if (aBean.getExtensionElements()!= null) {
            aBean.getExtensionElements().accept(aVisitor);
        }
    }

    @Override
    public void traverse(TConversationAssociation aBean, Visitor<?, E> aVisitor)
        throws E
    {
        for (TDocumentation bean: aBean.getDocumentation()) {
            bean.accept(aVisitor);
        }
        if (aBean.getExtensionElements()!= null) {
            aBean.getExtensionElements().accept(aVisitor);
        }
    }

    @Override
    public void traverse(TConversationLink aBean, Visitor<?, E> aVisitor)
        throws E
    {
        for (TDocumentation bean: aBean.getDocumentation()) {
            bean.accept(aVisitor);
        }
        if (aBean.getExtensionElements()!= null) {
            aBean.getExtensionElements().accept(aVisitor);
        }
    }

    @Override
    public void traverse(TCorrelationKey aBean, Visitor<?, E> aVisitor)
        throws E
    {
        for (TDocumentation bean: aBean.getDocumentation()) {
            bean.accept(aVisitor);
        }
        if (aBean.getExtensionElements()!= null) {
            aBean.getExtensionElements().accept(aVisitor);
        }
    }

    @Override
    public void traverse(TCorrelationProperty aBean, Visitor<?, E> aVisitor)
        throws E
    {
        for (TCorrelationPropertyRetrievalExpression bean: aBean.getCorrelationPropertyRetrievalExpression()) {
            bean.accept(aVisitor);
        }
        for (TDocumentation bean: aBean.getDocumentation()) {
            bean.accept(aVisitor);
        }
        if (aBean.getExtensionElements()!= null) {
            aBean.getExtensionElements().accept(aVisitor);
        }
    }

    @Override
    public void traverse(TCorrelationPropertyBinding aBean, Visitor<?, E> aVisitor)
        throws E
    {
        if (aBean.getDataPath()!= null) {
            aBean.getDataPath().accept(aVisitor);
        }
        for (TDocumentation bean: aBean.getDocumentation()) {
            bean.accept(aVisitor);
        }
        if (aBean.getExtensionElements()!= null) {
            aBean.getExtensionElements().accept(aVisitor);
        }
    }

    @Override
    public void traverse(TCorrelationPropertyRetrievalExpression aBean, Visitor<?, E> aVisitor)
        throws E
    {
        if (aBean.getMessagePath()!= null) {
            aBean.getMessagePath().accept(aVisitor);
        }
        for (TDocumentation bean: aBean.getDocumentation()) {
            bean.accept(aVisitor);
        }
        if (aBean.getExtensionElements()!= null) {
            aBean.getExtensionElements().accept(aVisitor);
        }
    }

    @Override
    public void traverse(TCorrelationSubscription aBean, Visitor<?, E> aVisitor)
        throws E
    {
        for (TCorrelationPropertyBinding bean: aBean.getCorrelationPropertyBinding()) {
            bean.accept(aVisitor);
        }
        for (TDocumentation bean: aBean.getDocumentation()) {
            bean.accept(aVisitor);
        }
        if (aBean.getExtensionElements()!= null) {
            aBean.getExtensionElements().accept(aVisitor);
        }
    }

    @Override
    public void traverse(TDataAssociation aBean, Visitor<?, E> aVisitor)
        throws E
    {
        for (JAXBElement<Object> obj: aBean.getSourceRef()) {
            if (obj.getValue() instanceof Visitable) {
                ((Visitable) obj.getValue()).accept(aVisitor);
            }
        }
        if (aBean.getTargetRef() instanceof Visitable) {
            ((Visitable) aBean.getTargetRef()).accept(aVisitor);
        }
        if (aBean.getTransformation()!= null) {
            aBean.getTransformation().accept(aVisitor);
        }
        for (TAssignment bean: aBean.getAssignment()) {
            bean.accept(aVisitor);
        }
        for (TDocumentation bean: aBean.getDocumentation()) {
            bean.accept(aVisitor);
        }
        if (aBean.getExtensionElements()!= null) {
            aBean.getExtensionElements().accept(aVisitor);
        }
    }

    @Override
    public void traverse(TDataInput aBean, Visitor<?, E> aVisitor)
        throws E
    {
        if (aBean.getDataState()!= null) {
            aBean.getDataState().accept(aVisitor);
        }
        for (TDocumentation bean: aBean.getDocumentation()) {
            bean.accept(aVisitor);
        }
        if (aBean.getExtensionElements()!= null) {
            aBean.getExtensionElements().accept(aVisitor);
        }
    }

    @Override
    public void traverse(TDataInputAssociation aBean, Visitor<?, E> aVisitor)
        throws E
    {
        for (JAXBElement<Object> obj: aBean.getSourceRef()) {
            if (obj.getValue() instanceof Visitable) {
                ((Visitable) obj.getValue()).accept(aVisitor);
            }
        }
        if (aBean.getTargetRef() instanceof Visitable) {
            ((Visitable) aBean.getTargetRef()).accept(aVisitor);
        }
        if (aBean.getTransformation()!= null) {
            aBean.getTransformation().accept(aVisitor);
        }
        for (TAssignment bean: aBean.getAssignment()) {
            bean.accept(aVisitor);
        }
        for (TDocumentation bean: aBean.getDocumentation()) {
            bean.accept(aVisitor);
        }
        if (aBean.getExtensionElements()!= null) {
            aBean.getExtensionElements().accept(aVisitor);
        }
    }

    @Override
    public void traverse(TDataObject aBean, Visitor<?, E> aVisitor)
        throws E
    {
        if (aBean.getDataState()!= null) {
            aBean.getDataState().accept(aVisitor);
        }
        if (aBean.getAuditing()!= null) {
            aBean.getAuditing().accept(aVisitor);
        }
        if (aBean.getMonitoring()!= null) {
            aBean.getMonitoring().accept(aVisitor);
        }
        for (TDocumentation bean: aBean.getDocumentation()) {
            bean.accept(aVisitor);
        }
        if (aBean.getExtensionElements()!= null) {
            aBean.getExtensionElements().accept(aVisitor);
        }
    }

    @Override
    public void traverse(TDataObjectReference aBean, Visitor<?, E> aVisitor)
        throws E
    {
        if (aBean.getDataState()!= null) {
            aBean.getDataState().accept(aVisitor);
        }
        if (aBean.getDataObjectRef() instanceof Visitable) {
            ((Visitable) aBean.getDataObjectRef()).accept(aVisitor);
        }
        if (aBean.getAuditing()!= null) {
            aBean.getAuditing().accept(aVisitor);
        }
        if (aBean.getMonitoring()!= null) {
            aBean.getMonitoring().accept(aVisitor);
        }
        for (TDocumentation bean: aBean.getDocumentation()) {
            bean.accept(aVisitor);
        }
        if (aBean.getExtensionElements()!= null) {
            aBean.getExtensionElements().accept(aVisitor);
        }
    }

    @Override
    public void traverse(TDataOutput aBean, Visitor<?, E> aVisitor)
        throws E
    {
        if (aBean.getDataState()!= null) {
            aBean.getDataState().accept(aVisitor);
        }
        for (TDocumentation bean: aBean.getDocumentation()) {
            bean.accept(aVisitor);
        }
        if (aBean.getExtensionElements()!= null) {
            aBean.getExtensionElements().accept(aVisitor);
        }
    }

    @Override
    public void traverse(TDataOutputAssociation aBean, Visitor<?, E> aVisitor)
        throws E
    {
        for (JAXBElement<Object> obj: aBean.getSourceRef()) {
            if (obj.getValue() instanceof Visitable) {
                ((Visitable) obj.getValue()).accept(aVisitor);
            }
        }
        if (aBean.getTargetRef() instanceof Visitable) {
            ((Visitable) aBean.getTargetRef()).accept(aVisitor);
        }
        if (aBean.getTransformation()!= null) {
            aBean.getTransformation().accept(aVisitor);
        }
        for (TAssignment bean: aBean.getAssignment()) {
            bean.accept(aVisitor);
        }
        for (TDocumentation bean: aBean.getDocumentation()) {
            bean.accept(aVisitor);
        }
        if (aBean.getExtensionElements()!= null) {
            aBean.getExtensionElements().accept(aVisitor);
        }
    }

    @Override
    public void traverse(TDataState aBean, Visitor<?, E> aVisitor)
        throws E
    {
        for (TDocumentation bean: aBean.getDocumentation()) {
            bean.accept(aVisitor);
        }
        if (aBean.getExtensionElements()!= null) {
            aBean.getExtensionElements().accept(aVisitor);
        }
    }

    @Override
    public void traverse(TDataStore aBean, Visitor<?, E> aVisitor)
        throws E
    {
        if (aBean.getDataState()!= null) {
            aBean.getDataState().accept(aVisitor);
        }
        for (TDocumentation bean: aBean.getDocumentation()) {
            bean.accept(aVisitor);
        }
        if (aBean.getExtensionElements()!= null) {
            aBean.getExtensionElements().accept(aVisitor);
        }
    }

    @Override
    public void traverse(TDataStoreReference aBean, Visitor<?, E> aVisitor)
        throws E
    {
        if (aBean.getDataState()!= null) {
            aBean.getDataState().accept(aVisitor);
        }
        if (aBean.getAuditing()!= null) {
            aBean.getAuditing().accept(aVisitor);
        }
        if (aBean.getMonitoring()!= null) {
            aBean.getMonitoring().accept(aVisitor);
        }
        for (TDocumentation bean: aBean.getDocumentation()) {
            bean.accept(aVisitor);
        }
        if (aBean.getExtensionElements()!= null) {
            aBean.getExtensionElements().accept(aVisitor);
        }
    }

    @Override
    public void traverse(TDefinitions aBean, Visitor<?, E> aVisitor)
        throws E
    {
        for (TImport bean: aBean.getImport()) {
            bean.accept(aVisitor);
        }
        for (TExtension bean: aBean.getExtension()) {
            bean.accept(aVisitor);
        }
        for (JAXBElement<? extends TRootElement> obj: aBean.getRootElement()) {
            if (obj.getValue()!= null) {
                obj.getValue().accept(aVisitor);
            }
        }
        for (BPMNDiagram bean: aBean.getBPMNDiagram()) {
            bean.accept(aVisitor);
        }
        for (TRelationship bean: aBean.getRelationship()) {
            bean.accept(aVisitor);
        }
    }

    @Override
    public void traverse(TDocumentation aBean, Visitor<?, E> aVisitor)
        throws E
    {
        for (Object bean: aBean.getContent()) {
            if (bean instanceof Visitable) {
                ((Visitable) bean).accept(aVisitor);
            } else {
                if (bean instanceof JAXBElement<?> ) {
                    if (((JAXBElement<?> ) bean).getValue() instanceof Visitable) {
                        ((Visitable)((JAXBElement<?> ) bean).getValue()).accept(aVisitor);
                    }
                }
            }
        }
    }

    @Override
    public void traverse(TEndEvent aBean, Visitor<?, E> aVisitor)
        throws E
    {
        for (TDataInput bean: aBean.getDataInput()) {
            bean.accept(aVisitor);
        }
        for (TDataInputAssociation bean: aBean.getDataInputAssociation()) {
            bean.accept(aVisitor);
        }
        if (aBean.getInputSet()!= null) {
            aBean.getInputSet().accept(aVisitor);
        }
        for (JAXBElement<? extends TEventDefinition> obj: aBean.getEventDefinition()) {
            if (obj.getValue()!= null) {
                obj.getValue().accept(aVisitor);
            }
        }
        for (TProperty bean: aBean.getProperty()) {
            bean.accept(aVisitor);
        }
        if (aBean.getAuditing()!= null) {
            aBean.getAuditing().accept(aVisitor);
        }
        if (aBean.getMonitoring()!= null) {
            aBean.getMonitoring().accept(aVisitor);
        }
        for (TDocumentation bean: aBean.getDocumentation()) {
            bean.accept(aVisitor);
        }
        if (aBean.getExtensionElements()!= null) {
            aBean.getExtensionElements().accept(aVisitor);
        }
    }

    @Override
    public void traverse(TEndPoint aBean, Visitor<?, E> aVisitor)
        throws E
    {
        for (TDocumentation bean: aBean.getDocumentation()) {
            bean.accept(aVisitor);
        }
        if (aBean.getExtensionElements()!= null) {
            aBean.getExtensionElements().accept(aVisitor);
        }
    }

    @Override
    public void traverse(TError aBean, Visitor<?, E> aVisitor)
        throws E
    {
        for (TDocumentation bean: aBean.getDocumentation()) {
            bean.accept(aVisitor);
        }
        if (aBean.getExtensionElements()!= null) {
            aBean.getExtensionElements().accept(aVisitor);
        }
    }

    @Override
    public void traverse(TErrorEventDefinition aBean, Visitor<?, E> aVisitor)
        throws E
    {
        for (TDocumentation bean: aBean.getDocumentation()) {
            bean.accept(aVisitor);
        }
        if (aBean.getExtensionElements()!= null) {
            aBean.getExtensionElements().accept(aVisitor);
        }
    }

    @Override
    public void traverse(TEscalation aBean, Visitor<?, E> aVisitor)
        throws E
    {
        for (TDocumentation bean: aBean.getDocumentation()) {
            bean.accept(aVisitor);
        }
        if (aBean.getExtensionElements()!= null) {
            aBean.getExtensionElements().accept(aVisitor);
        }
    }

    @Override
    public void traverse(TEscalationEventDefinition aBean, Visitor<?, E> aVisitor)
        throws E
    {
        for (TDocumentation bean: aBean.getDocumentation()) {
            bean.accept(aVisitor);
        }
        if (aBean.getExtensionElements()!= null) {
            aBean.getExtensionElements().accept(aVisitor);
        }
    }

    @Override
    public void traverse(TEventBasedGateway aBean, Visitor<?, E> aVisitor)
        throws E
    {
        if (aBean.getAuditing()!= null) {
            aBean.getAuditing().accept(aVisitor);
        }
        if (aBean.getMonitoring()!= null) {
            aBean.getMonitoring().accept(aVisitor);
        }
        for (TDocumentation bean: aBean.getDocumentation()) {
            bean.accept(aVisitor);
        }
        if (aBean.getExtensionElements()!= null) {
            aBean.getExtensionElements().accept(aVisitor);
        }
    }

    @Override
    public void traverse(TExclusiveGateway aBean, Visitor<?, E> aVisitor)
        throws E
    {
        if (aBean.getDefault() instanceof Visitable) {
            ((Visitable) aBean.getDefault()).accept(aVisitor);
        }
        if (aBean.getAuditing()!= null) {
            aBean.getAuditing().accept(aVisitor);
        }
        if (aBean.getMonitoring()!= null) {
            aBean.getMonitoring().accept(aVisitor);
        }
        for (TDocumentation bean: aBean.getDocumentation()) {
            bean.accept(aVisitor);
        }
        if (aBean.getExtensionElements()!= null) {
            aBean.getExtensionElements().accept(aVisitor);
        }
    }

    @Override
    public void traverse(TExpression aBean, Visitor<?, E> aVisitor)
        throws E
    {
        for (Serializable bean: aBean.getContent()) {
            if (bean instanceof Visitable) {
                ((Visitable) bean).accept(aVisitor);
            } else {
                if (bean instanceof JAXBElement<?> ) {
                    if (((JAXBElement<?> ) bean).getValue() instanceof Visitable) {
                        ((Visitable)((JAXBElement<?> ) bean).getValue()).accept(aVisitor);
                    }
                }
            }
        }
    }

    @Override
    public void traverse(TExtension aBean, Visitor<?, E> aVisitor)
        throws E
    {
        for (TDocumentation bean: aBean.getDocumentation()) {
            bean.accept(aVisitor);
        }
    }

    @Override
    public void traverse(TExtensionElements aBean, Visitor<?, E> aVisitor)
        throws E
    {
        for (Object bean: aBean.getAny()) {
            if (bean instanceof Visitable) {
                ((Visitable) bean).accept(aVisitor);
            } else {
                if (bean instanceof JAXBElement<?> ) {
                    if (((JAXBElement<?> ) bean).getValue() instanceof Visitable) {
                        ((Visitable)((JAXBElement<?> ) bean).getValue()).accept(aVisitor);
                    }
                }
            }
        }
    }

    @Override
    public void traverse(TFormalExpression aBean, Visitor<?, E> aVisitor)
        throws E
    {
        for (Serializable bean: aBean.getContent()) {
            if (bean instanceof Visitable) {
                ((Visitable) bean).accept(aVisitor);
            } else {
                if (bean instanceof JAXBElement<?> ) {
                    if (((JAXBElement<?> ) bean).getValue() instanceof Visitable) {
                        ((Visitable)((JAXBElement<?> ) bean).getValue()).accept(aVisitor);
                    }
                }
            }
        }
    }

    @Override
    public void traverse(TGateway aBean, Visitor<?, E> aVisitor)
        throws E
    {
        if (aBean.getAuditing()!= null) {
            aBean.getAuditing().accept(aVisitor);
        }
        if (aBean.getMonitoring()!= null) {
            aBean.getMonitoring().accept(aVisitor);
        }
        for (TDocumentation bean: aBean.getDocumentation()) {
            bean.accept(aVisitor);
        }
        if (aBean.getExtensionElements()!= null) {
            aBean.getExtensionElements().accept(aVisitor);
        }
    }

    @Override
    public void traverse(TGlobalBusinessRuleTask aBean, Visitor<?, E> aVisitor)
        throws E
    {
        for (JAXBElement<? extends TResourceRole> obj: aBean.getResourceRole()) {
            if (obj.getValue()!= null) {
                obj.getValue().accept(aVisitor);
            }
        }
        if (aBean.getIoSpecification()!= null) {
            aBean.getIoSpecification().accept(aVisitor);
        }
        for (TInputOutputBinding bean: aBean.getIoBinding()) {
            bean.accept(aVisitor);
        }
        for (TDocumentation bean: aBean.getDocumentation()) {
            bean.accept(aVisitor);
        }
        if (aBean.getExtensionElements()!= null) {
            aBean.getExtensionElements().accept(aVisitor);
        }
    }

    @Override
    public void traverse(TGlobalChoreographyTask aBean, Visitor<?, E> aVisitor)
        throws E
    {
        for (JAXBElement<? extends TFlowElement> obj: aBean.getFlowElement()) {
            if (obj.getValue()!= null) {
                obj.getValue().accept(aVisitor);
            }
        }
        for (TParticipant bean: aBean.getParticipant()) {
            bean.accept(aVisitor);
        }
        for (TMessageFlow bean: aBean.getMessageFlow()) {
            bean.accept(aVisitor);
        }
        for (JAXBElement<? extends TArtifact> obj: aBean.getArtifact()) {
            if (obj.getValue()!= null) {
                obj.getValue().accept(aVisitor);
            }
        }
        for (JAXBElement<? extends TConversationNode> obj: aBean.getConversationNode()) {
            if (obj.getValue()!= null) {
                obj.getValue().accept(aVisitor);
            }
        }
        for (TConversationAssociation bean: aBean.getConversationAssociation()) {
            bean.accept(aVisitor);
        }
        for (TParticipantAssociation bean: aBean.getParticipantAssociation()) {
            bean.accept(aVisitor);
        }
        for (TMessageFlowAssociation bean: aBean.getMessageFlowAssociation()) {
            bean.accept(aVisitor);
        }
        for (TCorrelationKey bean: aBean.getCorrelationKey()) {
            bean.accept(aVisitor);
        }
        for (TConversationLink bean: aBean.getConversationLink()) {
            bean.accept(aVisitor);
        }
        for (TDocumentation bean: aBean.getDocumentation()) {
            bean.accept(aVisitor);
        }
        if (aBean.getExtensionElements()!= null) {
            aBean.getExtensionElements().accept(aVisitor);
        }
    }

    @Override
    public void traverse(TGlobalConversation aBean, Visitor<?, E> aVisitor)
        throws E
    {
        for (TParticipant bean: aBean.getParticipant()) {
            bean.accept(aVisitor);
        }
        for (TMessageFlow bean: aBean.getMessageFlow()) {
            bean.accept(aVisitor);
        }
        for (JAXBElement<? extends TArtifact> obj: aBean.getArtifact()) {
            if (obj.getValue()!= null) {
                obj.getValue().accept(aVisitor);
            }
        }
        for (JAXBElement<? extends TConversationNode> obj: aBean.getConversationNode()) {
            if (obj.getValue()!= null) {
                obj.getValue().accept(aVisitor);
            }
        }
        for (TConversationAssociation bean: aBean.getConversationAssociation()) {
            bean.accept(aVisitor);
        }
        for (TParticipantAssociation bean: aBean.getParticipantAssociation()) {
            bean.accept(aVisitor);
        }
        for (TMessageFlowAssociation bean: aBean.getMessageFlowAssociation()) {
            bean.accept(aVisitor);
        }
        for (TCorrelationKey bean: aBean.getCorrelationKey()) {
            bean.accept(aVisitor);
        }
        for (TConversationLink bean: aBean.getConversationLink()) {
            bean.accept(aVisitor);
        }
        for (TDocumentation bean: aBean.getDocumentation()) {
            bean.accept(aVisitor);
        }
        if (aBean.getExtensionElements()!= null) {
            aBean.getExtensionElements().accept(aVisitor);
        }
    }

    @Override
    public void traverse(TGlobalManualTask aBean, Visitor<?, E> aVisitor)
        throws E
    {
        for (JAXBElement<? extends TResourceRole> obj: aBean.getResourceRole()) {
            if (obj.getValue()!= null) {
                obj.getValue().accept(aVisitor);
            }
        }
        if (aBean.getIoSpecification()!= null) {
            aBean.getIoSpecification().accept(aVisitor);
        }
        for (TInputOutputBinding bean: aBean.getIoBinding()) {
            bean.accept(aVisitor);
        }
        for (TDocumentation bean: aBean.getDocumentation()) {
            bean.accept(aVisitor);
        }
        if (aBean.getExtensionElements()!= null) {
            aBean.getExtensionElements().accept(aVisitor);
        }
    }

    @Override
    public void traverse(TGlobalScriptTask aBean, Visitor<?, E> aVisitor)
        throws E
    {
        if (aBean.getScript()!= null) {
            aBean.getScript().accept(aVisitor);
        }
        for (JAXBElement<? extends TResourceRole> obj: aBean.getResourceRole()) {
            if (obj.getValue()!= null) {
                obj.getValue().accept(aVisitor);
            }
        }
        if (aBean.getIoSpecification()!= null) {
            aBean.getIoSpecification().accept(aVisitor);
        }
        for (TInputOutputBinding bean: aBean.getIoBinding()) {
            bean.accept(aVisitor);
        }
        for (TDocumentation bean: aBean.getDocumentation()) {
            bean.accept(aVisitor);
        }
        if (aBean.getExtensionElements()!= null) {
            aBean.getExtensionElements().accept(aVisitor);
        }
    }

    @Override
    public void traverse(TGlobalTask aBean, Visitor<?, E> aVisitor)
        throws E
    {
        for (JAXBElement<? extends TResourceRole> obj: aBean.getResourceRole()) {
            if (obj.getValue()!= null) {
                obj.getValue().accept(aVisitor);
            }
        }
        if (aBean.getIoSpecification()!= null) {
            aBean.getIoSpecification().accept(aVisitor);
        }
        for (TInputOutputBinding bean: aBean.getIoBinding()) {
            bean.accept(aVisitor);
        }
        for (TDocumentation bean: aBean.getDocumentation()) {
            bean.accept(aVisitor);
        }
        if (aBean.getExtensionElements()!= null) {
            aBean.getExtensionElements().accept(aVisitor);
        }
    }

    @Override
    public void traverse(TGlobalUserTask aBean, Visitor<?, E> aVisitor)
        throws E
    {
        for (TRendering bean: aBean.getRendering()) {
            bean.accept(aVisitor);
        }
        for (JAXBElement<? extends TResourceRole> obj: aBean.getResourceRole()) {
            if (obj.getValue()!= null) {
                obj.getValue().accept(aVisitor);
            }
        }
        if (aBean.getIoSpecification()!= null) {
            aBean.getIoSpecification().accept(aVisitor);
        }
        for (TInputOutputBinding bean: aBean.getIoBinding()) {
            bean.accept(aVisitor);
        }
        for (TDocumentation bean: aBean.getDocumentation()) {
            bean.accept(aVisitor);
        }
        if (aBean.getExtensionElements()!= null) {
            aBean.getExtensionElements().accept(aVisitor);
        }
    }

    @Override
    public void traverse(TGroup aBean, Visitor<?, E> aVisitor)
        throws E
    {
        for (TDocumentation bean: aBean.getDocumentation()) {
            bean.accept(aVisitor);
        }
        if (aBean.getExtensionElements()!= null) {
            aBean.getExtensionElements().accept(aVisitor);
        }
    }

    @Override
    public void traverse(THumanPerformer aBean, Visitor<?, E> aVisitor)
        throws E
    {
        for (TResourceParameterBinding bean: aBean.getResourceParameterBinding()) {
            bean.accept(aVisitor);
        }
        if (aBean.getResourceAssignmentExpression()!= null) {
            aBean.getResourceAssignmentExpression().accept(aVisitor);
        }
        for (TDocumentation bean: aBean.getDocumentation()) {
            bean.accept(aVisitor);
        }
        if (aBean.getExtensionElements()!= null) {
            aBean.getExtensionElements().accept(aVisitor);
        }
    }

    @Override
    public void traverse(TImplicitThrowEvent aBean, Visitor<?, E> aVisitor)
        throws E
    {
        for (TDataInput bean: aBean.getDataInput()) {
            bean.accept(aVisitor);
        }
        for (TDataInputAssociation bean: aBean.getDataInputAssociation()) {
            bean.accept(aVisitor);
        }
        if (aBean.getInputSet()!= null) {
            aBean.getInputSet().accept(aVisitor);
        }
        for (JAXBElement<? extends TEventDefinition> obj: aBean.getEventDefinition()) {
            if (obj.getValue()!= null) {
                obj.getValue().accept(aVisitor);
            }
        }
        for (TProperty bean: aBean.getProperty()) {
            bean.accept(aVisitor);
        }
        if (aBean.getAuditing()!= null) {
            aBean.getAuditing().accept(aVisitor);
        }
        if (aBean.getMonitoring()!= null) {
            aBean.getMonitoring().accept(aVisitor);
        }
        for (TDocumentation bean: aBean.getDocumentation()) {
            bean.accept(aVisitor);
        }
        if (aBean.getExtensionElements()!= null) {
            aBean.getExtensionElements().accept(aVisitor);
        }
    }

    @Override
    public void traverse(TImport aBean, Visitor<?, E> aVisitor)
        throws E
    {
    }

    @Override
    public void traverse(TInclusiveGateway aBean, Visitor<?, E> aVisitor)
        throws E
    {
        if (aBean.getDefault() instanceof Visitable) {
            ((Visitable) aBean.getDefault()).accept(aVisitor);
        }
        if (aBean.getAuditing()!= null) {
            aBean.getAuditing().accept(aVisitor);
        }
        if (aBean.getMonitoring()!= null) {
            aBean.getMonitoring().accept(aVisitor);
        }
        for (TDocumentation bean: aBean.getDocumentation()) {
            bean.accept(aVisitor);
        }
        if (aBean.getExtensionElements()!= null) {
            aBean.getExtensionElements().accept(aVisitor);
        }
    }

    @Override
    public void traverse(TInputOutputBinding aBean, Visitor<?, E> aVisitor)
        throws E
    {
        if (aBean.getInputDataRef() instanceof Visitable) {
            ((Visitable) aBean.getInputDataRef()).accept(aVisitor);
        }
        if (aBean.getOutputDataRef() instanceof Visitable) {
            ((Visitable) aBean.getOutputDataRef()).accept(aVisitor);
        }
        for (TDocumentation bean: aBean.getDocumentation()) {
            bean.accept(aVisitor);
        }
        if (aBean.getExtensionElements()!= null) {
            aBean.getExtensionElements().accept(aVisitor);
        }
    }

    @Override
    public void traverse(TInputOutputSpecification aBean, Visitor<?, E> aVisitor)
        throws E
    {
        for (TDataInput bean: aBean.getDataInput()) {
            bean.accept(aVisitor);
        }
        for (TDataOutput bean: aBean.getDataOutput()) {
            bean.accept(aVisitor);
        }
        for (TInputSet bean: aBean.getInputSet()) {
            bean.accept(aVisitor);
        }
        for (TOutputSet bean: aBean.getOutputSet()) {
            bean.accept(aVisitor);
        }
        for (TDocumentation bean: aBean.getDocumentation()) {
            bean.accept(aVisitor);
        }
        if (aBean.getExtensionElements()!= null) {
            aBean.getExtensionElements().accept(aVisitor);
        }
    }

    @Override
    public void traverse(TInputSet aBean, Visitor<?, E> aVisitor)
        throws E
    {
        for (JAXBElement<Object> obj: aBean.getDataInputRefs()) {
            if (obj.getValue() instanceof Visitable) {
                ((Visitable) obj.getValue()).accept(aVisitor);
            }
        }
        for (JAXBElement<Object> obj: aBean.getOptionalInputRefs()) {
            if (obj.getValue() instanceof Visitable) {
                ((Visitable) obj.getValue()).accept(aVisitor);
            }
        }
        for (JAXBElement<Object> obj: aBean.getWhileExecutingInputRefs()) {
            if (obj.getValue() instanceof Visitable) {
                ((Visitable) obj.getValue()).accept(aVisitor);
            }
        }
        for (JAXBElement<Object> obj: aBean.getOutputSetRefs()) {
            if (obj.getValue() instanceof Visitable) {
                ((Visitable) obj.getValue()).accept(aVisitor);
            }
        }
        for (TDocumentation bean: aBean.getDocumentation()) {
            bean.accept(aVisitor);
        }
        if (aBean.getExtensionElements()!= null) {
            aBean.getExtensionElements().accept(aVisitor);
        }
    }

    @Override
    public void traverse(TInterface aBean, Visitor<?, E> aVisitor)
        throws E
    {
        for (TOperation bean: aBean.getOperation()) {
            bean.accept(aVisitor);
        }
        for (TDocumentation bean: aBean.getDocumentation()) {
            bean.accept(aVisitor);
        }
        if (aBean.getExtensionElements()!= null) {
            aBean.getExtensionElements().accept(aVisitor);
        }
    }

    @Override
    public void traverse(TIntermediateCatchEvent aBean, Visitor<?, E> aVisitor)
        throws E
    {
        for (TDataOutput bean: aBean.getDataOutput()) {
            bean.accept(aVisitor);
        }
        for (TDataOutputAssociation bean: aBean.getDataOutputAssociation()) {
            bean.accept(aVisitor);
        }
        if (aBean.getOutputSet()!= null) {
            aBean.getOutputSet().accept(aVisitor);
        }
        for (JAXBElement<? extends TEventDefinition> obj: aBean.getEventDefinition()) {
            if (obj.getValue()!= null) {
                obj.getValue().accept(aVisitor);
            }
        }
        for (TProperty bean: aBean.getProperty()) {
            bean.accept(aVisitor);
        }
        if (aBean.getAuditing()!= null) {
            aBean.getAuditing().accept(aVisitor);
        }
        if (aBean.getMonitoring()!= null) {
            aBean.getMonitoring().accept(aVisitor);
        }
        for (TDocumentation bean: aBean.getDocumentation()) {
            bean.accept(aVisitor);
        }
        if (aBean.getExtensionElements()!= null) {
            aBean.getExtensionElements().accept(aVisitor);
        }
    }

    @Override
    public void traverse(TIntermediateThrowEvent aBean, Visitor<?, E> aVisitor)
        throws E
    {
        for (TDataInput bean: aBean.getDataInput()) {
            bean.accept(aVisitor);
        }
        for (TDataInputAssociation bean: aBean.getDataInputAssociation()) {
            bean.accept(aVisitor);
        }
        if (aBean.getInputSet()!= null) {
            aBean.getInputSet().accept(aVisitor);
        }
        for (JAXBElement<? extends TEventDefinition> obj: aBean.getEventDefinition()) {
            if (obj.getValue()!= null) {
                obj.getValue().accept(aVisitor);
            }
        }
        for (TProperty bean: aBean.getProperty()) {
            bean.accept(aVisitor);
        }
        if (aBean.getAuditing()!= null) {
            aBean.getAuditing().accept(aVisitor);
        }
        if (aBean.getMonitoring()!= null) {
            aBean.getMonitoring().accept(aVisitor);
        }
        for (TDocumentation bean: aBean.getDocumentation()) {
            bean.accept(aVisitor);
        }
        if (aBean.getExtensionElements()!= null) {
            aBean.getExtensionElements().accept(aVisitor);
        }
    }

    @Override
    public void traverse(TItemDefinition aBean, Visitor<?, E> aVisitor)
        throws E
    {
        for (TDocumentation bean: aBean.getDocumentation()) {
            bean.accept(aVisitor);
        }
        if (aBean.getExtensionElements()!= null) {
            aBean.getExtensionElements().accept(aVisitor);
        }
    }

    @Override
    public void traverse(TLane aBean, Visitor<?, E> aVisitor)
        throws E
    {
        if (aBean.getPartitionElement()!= null) {
            aBean.getPartitionElement().accept(aVisitor);
        }
        for (JAXBElement<Object> obj: aBean.getFlowNodeRef()) {
            if (obj.getValue() instanceof Visitable) {
                ((Visitable) obj.getValue()).accept(aVisitor);
            }
        }
        if (aBean.getChildLaneSet()!= null) {
            aBean.getChildLaneSet().accept(aVisitor);
        }
        for (TDocumentation bean: aBean.getDocumentation()) {
            bean.accept(aVisitor);
        }
        if (aBean.getExtensionElements()!= null) {
            aBean.getExtensionElements().accept(aVisitor);
        }
    }

    @Override
    public void traverse(TLaneSet aBean, Visitor<?, E> aVisitor)
        throws E
    {
        for (TLane bean: aBean.getLane()) {
            bean.accept(aVisitor);
        }
        for (TDocumentation bean: aBean.getDocumentation()) {
            bean.accept(aVisitor);
        }
        if (aBean.getExtensionElements()!= null) {
            aBean.getExtensionElements().accept(aVisitor);
        }
    }

    @Override
    public void traverse(TLinkEventDefinition aBean, Visitor<?, E> aVisitor)
        throws E
    {
        for (TDocumentation bean: aBean.getDocumentation()) {
            bean.accept(aVisitor);
        }
        if (aBean.getExtensionElements()!= null) {
            aBean.getExtensionElements().accept(aVisitor);
        }
    }

    @Override
    public void traverse(TManualTask aBean, Visitor<?, E> aVisitor)
        throws E
    {
        if (aBean.getIoSpecification()!= null) {
            aBean.getIoSpecification().accept(aVisitor);
        }
        for (TProperty bean: aBean.getProperty()) {
            bean.accept(aVisitor);
        }
        for (TDataInputAssociation bean: aBean.getDataInputAssociation()) {
            bean.accept(aVisitor);
        }
        for (TDataOutputAssociation bean: aBean.getDataOutputAssociation()) {
            bean.accept(aVisitor);
        }
        for (JAXBElement<? extends TResourceRole> obj: aBean.getResourceRole()) {
            if (obj.getValue()!= null) {
                obj.getValue().accept(aVisitor);
            }
        }
        if (aBean.getLoopCharacteristics()!= null) {
            aBean.getLoopCharacteristics().getValue().accept(aVisitor);
        }
        if (aBean.getDefault() instanceof Visitable) {
            ((Visitable) aBean.getDefault()).accept(aVisitor);
        }
        if (aBean.getAuditing()!= null) {
            aBean.getAuditing().accept(aVisitor);
        }
        if (aBean.getMonitoring()!= null) {
            aBean.getMonitoring().accept(aVisitor);
        }
        for (TDocumentation bean: aBean.getDocumentation()) {
            bean.accept(aVisitor);
        }
        if (aBean.getExtensionElements()!= null) {
            aBean.getExtensionElements().accept(aVisitor);
        }
    }

    @Override
    public void traverse(TMessage aBean, Visitor<?, E> aVisitor)
        throws E
    {
        for (TDocumentation bean: aBean.getDocumentation()) {
            bean.accept(aVisitor);
        }
        if (aBean.getExtensionElements()!= null) {
            aBean.getExtensionElements().accept(aVisitor);
        }
    }

    @Override
    public void traverse(TMessageEventDefinition aBean, Visitor<?, E> aVisitor)
        throws E
    {
        for (TDocumentation bean: aBean.getDocumentation()) {
            bean.accept(aVisitor);
        }
        if (aBean.getExtensionElements()!= null) {
            aBean.getExtensionElements().accept(aVisitor);
        }
    }

    @Override
    public void traverse(TMessageFlow aBean, Visitor<?, E> aVisitor)
        throws E
    {
        for (TDocumentation bean: aBean.getDocumentation()) {
            bean.accept(aVisitor);
        }
        if (aBean.getExtensionElements()!= null) {
            aBean.getExtensionElements().accept(aVisitor);
        }
    }

    @Override
    public void traverse(TMessageFlowAssociation aBean, Visitor<?, E> aVisitor)
        throws E
    {
        for (TDocumentation bean: aBean.getDocumentation()) {
            bean.accept(aVisitor);
        }
        if (aBean.getExtensionElements()!= null) {
            aBean.getExtensionElements().accept(aVisitor);
        }
    }

    @Override
    public void traverse(TMonitoring aBean, Visitor<?, E> aVisitor)
        throws E
    {
        for (TDocumentation bean: aBean.getDocumentation()) {
            bean.accept(aVisitor);
        }
        if (aBean.getExtensionElements()!= null) {
            aBean.getExtensionElements().accept(aVisitor);
        }
    }

    @Override
    public void traverse(TMultiInstanceLoopCharacteristics aBean, Visitor<?, E> aVisitor)
        throws E
    {
        if (aBean.getLoopCardinality()!= null) {
            aBean.getLoopCardinality().accept(aVisitor);
        }
        if (aBean.getInputDataItem()!= null) {
            aBean.getInputDataItem().accept(aVisitor);
        }
        if (aBean.getOutputDataItem()!= null) {
            aBean.getOutputDataItem().accept(aVisitor);
        }
        for (TComplexBehaviorDefinition bean: aBean.getComplexBehaviorDefinition()) {
            bean.accept(aVisitor);
        }
        if (aBean.getCompletionCondition()!= null) {
            aBean.getCompletionCondition().accept(aVisitor);
        }
        for (TDocumentation bean: aBean.getDocumentation()) {
            bean.accept(aVisitor);
        }
        if (aBean.getExtensionElements()!= null) {
            aBean.getExtensionElements().accept(aVisitor);
        }
    }

    @Override
    public void traverse(TOperation aBean, Visitor<?, E> aVisitor)
        throws E
    {
        for (TDocumentation bean: aBean.getDocumentation()) {
            bean.accept(aVisitor);
        }
        if (aBean.getExtensionElements()!= null) {
            aBean.getExtensionElements().accept(aVisitor);
        }
    }

    @Override
    public void traverse(TOutputSet aBean, Visitor<?, E> aVisitor)
        throws E
    {
        for (JAXBElement<Object> obj: aBean.getDataOutputRefs()) {
            if (obj.getValue() instanceof Visitable) {
                ((Visitable) obj.getValue()).accept(aVisitor);
            }
        }
        for (JAXBElement<Object> obj: aBean.getOptionalOutputRefs()) {
            if (obj.getValue() instanceof Visitable) {
                ((Visitable) obj.getValue()).accept(aVisitor);
            }
        }
        for (JAXBElement<Object> obj: aBean.getWhileExecutingOutputRefs()) {
            if (obj.getValue() instanceof Visitable) {
                ((Visitable) obj.getValue()).accept(aVisitor);
            }
        }
        for (JAXBElement<Object> obj: aBean.getInputSetRefs()) {
            if (obj.getValue() instanceof Visitable) {
                ((Visitable) obj.getValue()).accept(aVisitor);
            }
        }
        for (TDocumentation bean: aBean.getDocumentation()) {
            bean.accept(aVisitor);
        }
        if (aBean.getExtensionElements()!= null) {
            aBean.getExtensionElements().accept(aVisitor);
        }
    }

    @Override
    public void traverse(TParallelGateway aBean, Visitor<?, E> aVisitor)
        throws E
    {
        if (aBean.getAuditing()!= null) {
            aBean.getAuditing().accept(aVisitor);
        }
        if (aBean.getMonitoring()!= null) {
            aBean.getMonitoring().accept(aVisitor);
        }
        for (TDocumentation bean: aBean.getDocumentation()) {
            bean.accept(aVisitor);
        }
        if (aBean.getExtensionElements()!= null) {
            aBean.getExtensionElements().accept(aVisitor);
        }
    }

    @Override
    public void traverse(TParticipant aBean, Visitor<?, E> aVisitor)
        throws E
    {
        if (aBean.getParticipantMultiplicity()!= null) {
            aBean.getParticipantMultiplicity().accept(aVisitor);
        }
        for (TDocumentation bean: aBean.getDocumentation()) {
            bean.accept(aVisitor);
        }
        if (aBean.getExtensionElements()!= null) {
            aBean.getExtensionElements().accept(aVisitor);
        }
    }

    @Override
    public void traverse(TParticipantAssociation aBean, Visitor<?, E> aVisitor)
        throws E
    {
        for (TDocumentation bean: aBean.getDocumentation()) {
            bean.accept(aVisitor);
        }
        if (aBean.getExtensionElements()!= null) {
            aBean.getExtensionElements().accept(aVisitor);
        }
    }

    @Override
    public void traverse(TParticipantMultiplicity aBean, Visitor<?, E> aVisitor)
        throws E
    {
        for (TDocumentation bean: aBean.getDocumentation()) {
            bean.accept(aVisitor);
        }
        if (aBean.getExtensionElements()!= null) {
            aBean.getExtensionElements().accept(aVisitor);
        }
    }

    @Override
    public void traverse(TPartnerEntity aBean, Visitor<?, E> aVisitor)
        throws E
    {
        for (TDocumentation bean: aBean.getDocumentation()) {
            bean.accept(aVisitor);
        }
        if (aBean.getExtensionElements()!= null) {
            aBean.getExtensionElements().accept(aVisitor);
        }
    }

    @Override
    public void traverse(TPartnerRole aBean, Visitor<?, E> aVisitor)
        throws E
    {
        for (TDocumentation bean: aBean.getDocumentation()) {
            bean.accept(aVisitor);
        }
        if (aBean.getExtensionElements()!= null) {
            aBean.getExtensionElements().accept(aVisitor);
        }
    }

    @Override
    public void traverse(TPerformer aBean, Visitor<?, E> aVisitor)
        throws E
    {
        for (TResourceParameterBinding bean: aBean.getResourceParameterBinding()) {
            bean.accept(aVisitor);
        }
        if (aBean.getResourceAssignmentExpression()!= null) {
            aBean.getResourceAssignmentExpression().accept(aVisitor);
        }
        for (TDocumentation bean: aBean.getDocumentation()) {
            bean.accept(aVisitor);
        }
        if (aBean.getExtensionElements()!= null) {
            aBean.getExtensionElements().accept(aVisitor);
        }
    }

    @Override
    public void traverse(TPotentialOwner aBean, Visitor<?, E> aVisitor)
        throws E
    {
        for (TResourceParameterBinding bean: aBean.getResourceParameterBinding()) {
            bean.accept(aVisitor);
        }
        if (aBean.getResourceAssignmentExpression()!= null) {
            aBean.getResourceAssignmentExpression().accept(aVisitor);
        }
        for (TDocumentation bean: aBean.getDocumentation()) {
            bean.accept(aVisitor);
        }
        if (aBean.getExtensionElements()!= null) {
            aBean.getExtensionElements().accept(aVisitor);
        }
    }

    @Override
    public void traverse(TProcess aBean, Visitor<?, E> aVisitor)
        throws E
    {
        if (aBean.getAuditing()!= null) {
            aBean.getAuditing().accept(aVisitor);
        }
        if (aBean.getMonitoring()!= null) {
            aBean.getMonitoring().accept(aVisitor);
        }
        for (TProperty bean: aBean.getProperty()) {
            bean.accept(aVisitor);
        }
        for (TLaneSet bean: aBean.getLaneSet()) {
            bean.accept(aVisitor);
        }
        for (JAXBElement<? extends TFlowElement> obj: aBean.getFlowElement()) {
            if (obj.getValue()!= null) {
                obj.getValue().accept(aVisitor);
            }
        }
        for (JAXBElement<? extends TArtifact> obj: aBean.getArtifact()) {
            if (obj.getValue()!= null) {
                obj.getValue().accept(aVisitor);
            }
        }
        for (JAXBElement<? extends TResourceRole> obj: aBean.getResourceRole()) {
            if (obj.getValue()!= null) {
                obj.getValue().accept(aVisitor);
            }
        }
        for (TCorrelationSubscription bean: aBean.getCorrelationSubscription()) {
            bean.accept(aVisitor);
        }
        if (aBean.getIoSpecification()!= null) {
            aBean.getIoSpecification().accept(aVisitor);
        }
        for (TInputOutputBinding bean: aBean.getIoBinding()) {
            bean.accept(aVisitor);
        }
        for (TDocumentation bean: aBean.getDocumentation()) {
            bean.accept(aVisitor);
        }
        if (aBean.getExtensionElements()!= null) {
            aBean.getExtensionElements().accept(aVisitor);
        }
    }

    @Override
    public void traverse(TProperty aBean, Visitor<?, E> aVisitor)
        throws E
    {
        if (aBean.getDataState()!= null) {
            aBean.getDataState().accept(aVisitor);
        }
        for (TDocumentation bean: aBean.getDocumentation()) {
            bean.accept(aVisitor);
        }
        if (aBean.getExtensionElements()!= null) {
            aBean.getExtensionElements().accept(aVisitor);
        }
    }

    @Override
    public void traverse(TReceiveTask aBean, Visitor<?, E> aVisitor)
        throws E
    {
        if (aBean.getIoSpecification()!= null) {
            aBean.getIoSpecification().accept(aVisitor);
        }
        for (TProperty bean: aBean.getProperty()) {
            bean.accept(aVisitor);
        }
        for (TDataInputAssociation bean: aBean.getDataInputAssociation()) {
            bean.accept(aVisitor);
        }
        for (TDataOutputAssociation bean: aBean.getDataOutputAssociation()) {
            bean.accept(aVisitor);
        }
        for (JAXBElement<? extends TResourceRole> obj: aBean.getResourceRole()) {
            if (obj.getValue()!= null) {
                obj.getValue().accept(aVisitor);
            }
        }
        if (aBean.getLoopCharacteristics()!= null) {
            aBean.getLoopCharacteristics().getValue().accept(aVisitor);
        }
        if (aBean.getDefault() instanceof Visitable) {
            ((Visitable) aBean.getDefault()).accept(aVisitor);
        }
        if (aBean.getAuditing()!= null) {
            aBean.getAuditing().accept(aVisitor);
        }
        if (aBean.getMonitoring()!= null) {
            aBean.getMonitoring().accept(aVisitor);
        }
        for (TDocumentation bean: aBean.getDocumentation()) {
            bean.accept(aVisitor);
        }
        if (aBean.getExtensionElements()!= null) {
            aBean.getExtensionElements().accept(aVisitor);
        }
    }

    @Override
    public void traverse(TRelationship aBean, Visitor<?, E> aVisitor)
        throws E
    {
        for (TDocumentation bean: aBean.getDocumentation()) {
            bean.accept(aVisitor);
        }
        if (aBean.getExtensionElements()!= null) {
            aBean.getExtensionElements().accept(aVisitor);
        }
    }

    @Override
    public void traverse(TRendering aBean, Visitor<?, E> aVisitor)
        throws E
    {
        for (TDocumentation bean: aBean.getDocumentation()) {
            bean.accept(aVisitor);
        }
        if (aBean.getExtensionElements()!= null) {
            aBean.getExtensionElements().accept(aVisitor);
        }
    }

    @Override
    public void traverse(TResource aBean, Visitor<?, E> aVisitor)
        throws E
    {
        for (TResourceParameter bean: aBean.getResourceParameter()) {
            bean.accept(aVisitor);
        }
        for (TDocumentation bean: aBean.getDocumentation()) {
            bean.accept(aVisitor);
        }
        if (aBean.getExtensionElements()!= null) {
            aBean.getExtensionElements().accept(aVisitor);
        }
    }

    @Override
    public void traverse(TResourceAssignmentExpression aBean, Visitor<?, E> aVisitor)
        throws E
    {
        if (aBean.getExpression()!= null) {
            aBean.getExpression().getValue().accept(aVisitor);
        }
        for (TDocumentation bean: aBean.getDocumentation()) {
            bean.accept(aVisitor);
        }
        if (aBean.getExtensionElements()!= null) {
            aBean.getExtensionElements().accept(aVisitor);
        }
    }

    @Override
    public void traverse(TResourceParameter aBean, Visitor<?, E> aVisitor)
        throws E
    {
        for (TDocumentation bean: aBean.getDocumentation()) {
            bean.accept(aVisitor);
        }
        if (aBean.getExtensionElements()!= null) {
            aBean.getExtensionElements().accept(aVisitor);
        }
    }

    @Override
    public void traverse(TResourceParameterBinding aBean, Visitor<?, E> aVisitor)
        throws E
    {
        if (aBean.getExpression()!= null) {
            aBean.getExpression().getValue().accept(aVisitor);
        }
        for (TDocumentation bean: aBean.getDocumentation()) {
            bean.accept(aVisitor);
        }
        if (aBean.getExtensionElements()!= null) {
            aBean.getExtensionElements().accept(aVisitor);
        }
    }

    @Override
    public void traverse(TResourceRole aBean, Visitor<?, E> aVisitor)
        throws E
    {
        for (TResourceParameterBinding bean: aBean.getResourceParameterBinding()) {
            bean.accept(aVisitor);
        }
        if (aBean.getResourceAssignmentExpression()!= null) {
            aBean.getResourceAssignmentExpression().accept(aVisitor);
        }
        for (TDocumentation bean: aBean.getDocumentation()) {
            bean.accept(aVisitor);
        }
        if (aBean.getExtensionElements()!= null) {
            aBean.getExtensionElements().accept(aVisitor);
        }
    }

    @Override
    public void traverse(TScript aBean, Visitor<?, E> aVisitor)
        throws E
    {
        for (Object bean: aBean.getContent()) {
            if (bean instanceof Visitable) {
                ((Visitable) bean).accept(aVisitor);
            } else {
                if (bean instanceof JAXBElement<?> ) {
                    if (((JAXBElement<?> ) bean).getValue() instanceof Visitable) {
                        ((Visitable)((JAXBElement<?> ) bean).getValue()).accept(aVisitor);
                    }
                }
            }
        }
    }

    @Override
    public void traverse(TScriptTask aBean, Visitor<?, E> aVisitor)
        throws E
    {
        if (aBean.getScript()!= null) {
            aBean.getScript().accept(aVisitor);
        }
        if (aBean.getIoSpecification()!= null) {
            aBean.getIoSpecification().accept(aVisitor);
        }
        for (TProperty bean: aBean.getProperty()) {
            bean.accept(aVisitor);
        }
        for (TDataInputAssociation bean: aBean.getDataInputAssociation()) {
            bean.accept(aVisitor);
        }
        for (TDataOutputAssociation bean: aBean.getDataOutputAssociation()) {
            bean.accept(aVisitor);
        }
        for (JAXBElement<? extends TResourceRole> obj: aBean.getResourceRole()) {
            if (obj.getValue()!= null) {
                obj.getValue().accept(aVisitor);
            }
        }
        if (aBean.getLoopCharacteristics()!= null) {
            aBean.getLoopCharacteristics().getValue().accept(aVisitor);
        }
        if (aBean.getDefault() instanceof Visitable) {
            ((Visitable) aBean.getDefault()).accept(aVisitor);
        }
        if (aBean.getAuditing()!= null) {
            aBean.getAuditing().accept(aVisitor);
        }
        if (aBean.getMonitoring()!= null) {
            aBean.getMonitoring().accept(aVisitor);
        }
        for (TDocumentation bean: aBean.getDocumentation()) {
            bean.accept(aVisitor);
        }
        if (aBean.getExtensionElements()!= null) {
            aBean.getExtensionElements().accept(aVisitor);
        }
    }

    @Override
    public void traverse(TSendTask aBean, Visitor<?, E> aVisitor)
        throws E
    {
        if (aBean.getIoSpecification()!= null) {
            aBean.getIoSpecification().accept(aVisitor);
        }
        for (TProperty bean: aBean.getProperty()) {
            bean.accept(aVisitor);
        }
        for (TDataInputAssociation bean: aBean.getDataInputAssociation()) {
            bean.accept(aVisitor);
        }
        for (TDataOutputAssociation bean: aBean.getDataOutputAssociation()) {
            bean.accept(aVisitor);
        }
        for (JAXBElement<? extends TResourceRole> obj: aBean.getResourceRole()) {
            if (obj.getValue()!= null) {
                obj.getValue().accept(aVisitor);
            }
        }
        if (aBean.getLoopCharacteristics()!= null) {
            aBean.getLoopCharacteristics().getValue().accept(aVisitor);
        }
        if (aBean.getDefault() instanceof Visitable) {
            ((Visitable) aBean.getDefault()).accept(aVisitor);
        }
        if (aBean.getAuditing()!= null) {
            aBean.getAuditing().accept(aVisitor);
        }
        if (aBean.getMonitoring()!= null) {
            aBean.getMonitoring().accept(aVisitor);
        }
        for (TDocumentation bean: aBean.getDocumentation()) {
            bean.accept(aVisitor);
        }
        if (aBean.getExtensionElements()!= null) {
            aBean.getExtensionElements().accept(aVisitor);
        }
    }

    @Override
    public void traverse(TSequenceFlow aBean, Visitor<?, E> aVisitor)
        throws E
    {
        if (aBean.getConditionExpression()!= null) {
            aBean.getConditionExpression().accept(aVisitor);
        }
        if (aBean.getSourceRef() instanceof Visitable) {
            ((Visitable) aBean.getSourceRef()).accept(aVisitor);
        }
        if (aBean.getTargetRef() instanceof Visitable) {
            ((Visitable) aBean.getTargetRef()).accept(aVisitor);
        }
        if (aBean.getAuditing()!= null) {
            aBean.getAuditing().accept(aVisitor);
        }
        if (aBean.getMonitoring()!= null) {
            aBean.getMonitoring().accept(aVisitor);
        }
        for (TDocumentation bean: aBean.getDocumentation()) {
            bean.accept(aVisitor);
        }
        if (aBean.getExtensionElements()!= null) {
            aBean.getExtensionElements().accept(aVisitor);
        }
    }

    @Override
    public void traverse(TServiceTask aBean, Visitor<?, E> aVisitor)
        throws E
    {
        if (aBean.getIoSpecification()!= null) {
            aBean.getIoSpecification().accept(aVisitor);
        }
        for (TProperty bean: aBean.getProperty()) {
            bean.accept(aVisitor);
        }
        for (TDataInputAssociation bean: aBean.getDataInputAssociation()) {
            bean.accept(aVisitor);
        }
        for (TDataOutputAssociation bean: aBean.getDataOutputAssociation()) {
            bean.accept(aVisitor);
        }
        for (JAXBElement<? extends TResourceRole> obj: aBean.getResourceRole()) {
            if (obj.getValue()!= null) {
                obj.getValue().accept(aVisitor);
            }
        }
        if (aBean.getLoopCharacteristics()!= null) {
            aBean.getLoopCharacteristics().getValue().accept(aVisitor);
        }
        if (aBean.getDefault() instanceof Visitable) {
            ((Visitable) aBean.getDefault()).accept(aVisitor);
        }
        if (aBean.getAuditing()!= null) {
            aBean.getAuditing().accept(aVisitor);
        }
        if (aBean.getMonitoring()!= null) {
            aBean.getMonitoring().accept(aVisitor);
        }
        for (TDocumentation bean: aBean.getDocumentation()) {
            bean.accept(aVisitor);
        }
        if (aBean.getExtensionElements()!= null) {
            aBean.getExtensionElements().accept(aVisitor);
        }
    }

    @Override
    public void traverse(TSignal aBean, Visitor<?, E> aVisitor)
        throws E
    {
        for (TDocumentation bean: aBean.getDocumentation()) {
            bean.accept(aVisitor);
        }
        if (aBean.getExtensionElements()!= null) {
            aBean.getExtensionElements().accept(aVisitor);
        }
    }

    @Override
    public void traverse(TSignalEventDefinition aBean, Visitor<?, E> aVisitor)
        throws E
    {
        for (TDocumentation bean: aBean.getDocumentation()) {
            bean.accept(aVisitor);
        }
        if (aBean.getExtensionElements()!= null) {
            aBean.getExtensionElements().accept(aVisitor);
        }
    }

    @Override
    public void traverse(TStandardLoopCharacteristics aBean, Visitor<?, E> aVisitor)
        throws E
    {
        if (aBean.getLoopCondition()!= null) {
            aBean.getLoopCondition().accept(aVisitor);
        }
        for (TDocumentation bean: aBean.getDocumentation()) {
            bean.accept(aVisitor);
        }
        if (aBean.getExtensionElements()!= null) {
            aBean.getExtensionElements().accept(aVisitor);
        }
    }

    @Override
    public void traverse(TStartEvent aBean, Visitor<?, E> aVisitor)
        throws E
    {
        for (TDataOutput bean: aBean.getDataOutput()) {
            bean.accept(aVisitor);
        }
        for (TDataOutputAssociation bean: aBean.getDataOutputAssociation()) {
            bean.accept(aVisitor);
        }
        if (aBean.getOutputSet()!= null) {
            aBean.getOutputSet().accept(aVisitor);
        }
        for (JAXBElement<? extends TEventDefinition> obj: aBean.getEventDefinition()) {
            if (obj.getValue()!= null) {
                obj.getValue().accept(aVisitor);
            }
        }
        for (TProperty bean: aBean.getProperty()) {
            bean.accept(aVisitor);
        }
        if (aBean.getAuditing()!= null) {
            aBean.getAuditing().accept(aVisitor);
        }
        if (aBean.getMonitoring()!= null) {
            aBean.getMonitoring().accept(aVisitor);
        }
        for (TDocumentation bean: aBean.getDocumentation()) {
            bean.accept(aVisitor);
        }
        if (aBean.getExtensionElements()!= null) {
            aBean.getExtensionElements().accept(aVisitor);
        }
    }

    @Override
    public void traverse(TSubChoreography aBean, Visitor<?, E> aVisitor)
        throws E
    {
        for (JAXBElement<? extends TFlowElement> obj: aBean.getFlowElement()) {
            if (obj.getValue()!= null) {
                obj.getValue().accept(aVisitor);
            }
        }
        for (JAXBElement<? extends TArtifact> obj: aBean.getArtifact()) {
            if (obj.getValue()!= null) {
                obj.getValue().accept(aVisitor);
            }
        }
        for (TCorrelationKey bean: aBean.getCorrelationKey()) {
            bean.accept(aVisitor);
        }
        if (aBean.getAuditing()!= null) {
            aBean.getAuditing().accept(aVisitor);
        }
        if (aBean.getMonitoring()!= null) {
            aBean.getMonitoring().accept(aVisitor);
        }
        for (TDocumentation bean: aBean.getDocumentation()) {
            bean.accept(aVisitor);
        }
        if (aBean.getExtensionElements()!= null) {
            aBean.getExtensionElements().accept(aVisitor);
        }
    }

    @Override
    public void traverse(TSubConversation aBean, Visitor<?, E> aVisitor)
        throws E
    {
        for (JAXBElement<? extends TConversationNode> obj: aBean.getConversationNode()) {
            if (obj.getValue()!= null) {
                obj.getValue().accept(aVisitor);
            }
        }
        for (TCorrelationKey bean: aBean.getCorrelationKey()) {
            bean.accept(aVisitor);
        }
        for (TDocumentation bean: aBean.getDocumentation()) {
            bean.accept(aVisitor);
        }
        if (aBean.getExtensionElements()!= null) {
            aBean.getExtensionElements().accept(aVisitor);
        }
    }

    @Override
    public void traverse(TSubProcess aBean, Visitor<?, E> aVisitor)
        throws E
    {
        for (TLaneSet bean: aBean.getLaneSet()) {
            bean.accept(aVisitor);
        }
        for (JAXBElement<? extends TFlowElement> obj: aBean.getFlowElement()) {
            if (obj.getValue()!= null) {
                obj.getValue().accept(aVisitor);
            }
        }
        for (JAXBElement<? extends TArtifact> obj: aBean.getArtifact()) {
            if (obj.getValue()!= null) {
                obj.getValue().accept(aVisitor);
            }
        }
        if (aBean.getIoSpecification()!= null) {
            aBean.getIoSpecification().accept(aVisitor);
        }
        for (TProperty bean: aBean.getProperty()) {
            bean.accept(aVisitor);
        }
        for (TDataInputAssociation bean: aBean.getDataInputAssociation()) {
            bean.accept(aVisitor);
        }
        for (TDataOutputAssociation bean: aBean.getDataOutputAssociation()) {
            bean.accept(aVisitor);
        }
        for (JAXBElement<? extends TResourceRole> obj: aBean.getResourceRole()) {
            if (obj.getValue()!= null) {
                obj.getValue().accept(aVisitor);
            }
        }
        if (aBean.getLoopCharacteristics()!= null) {
            aBean.getLoopCharacteristics().getValue().accept(aVisitor);
        }
        if (aBean.getDefault() instanceof Visitable) {
            ((Visitable) aBean.getDefault()).accept(aVisitor);
        }
        if (aBean.getAuditing()!= null) {
            aBean.getAuditing().accept(aVisitor);
        }
        if (aBean.getMonitoring()!= null) {
            aBean.getMonitoring().accept(aVisitor);
        }
        for (TDocumentation bean: aBean.getDocumentation()) {
            bean.accept(aVisitor);
        }
        if (aBean.getExtensionElements()!= null) {
            aBean.getExtensionElements().accept(aVisitor);
        }
    }

    @Override
    public void traverse(TTask aBean, Visitor<?, E> aVisitor)
        throws E
    {
        if (aBean.getIoSpecification()!= null) {
            aBean.getIoSpecification().accept(aVisitor);
        }
        for (TProperty bean: aBean.getProperty()) {
            bean.accept(aVisitor);
        }
        for (TDataInputAssociation bean: aBean.getDataInputAssociation()) {
            bean.accept(aVisitor);
        }
        for (TDataOutputAssociation bean: aBean.getDataOutputAssociation()) {
            bean.accept(aVisitor);
        }
        for (JAXBElement<? extends TResourceRole> obj: aBean.getResourceRole()) {
            if (obj.getValue()!= null) {
                obj.getValue().accept(aVisitor);
            }
        }
        if (aBean.getLoopCharacteristics()!= null) {
            aBean.getLoopCharacteristics().getValue().accept(aVisitor);
        }
        if (aBean.getDefault() instanceof Visitable) {
            ((Visitable) aBean.getDefault()).accept(aVisitor);
        }
        if (aBean.getAuditing()!= null) {
            aBean.getAuditing().accept(aVisitor);
        }
        if (aBean.getMonitoring()!= null) {
            aBean.getMonitoring().accept(aVisitor);
        }
        for (TDocumentation bean: aBean.getDocumentation()) {
            bean.accept(aVisitor);
        }
        if (aBean.getExtensionElements()!= null) {
            aBean.getExtensionElements().accept(aVisitor);
        }
    }

    @Override
    public void traverse(TTerminateEventDefinition aBean, Visitor<?, E> aVisitor)
        throws E
    {
        for (TDocumentation bean: aBean.getDocumentation()) {
            bean.accept(aVisitor);
        }
        if (aBean.getExtensionElements()!= null) {
            aBean.getExtensionElements().accept(aVisitor);
        }
    }

    @Override
    public void traverse(TText aBean, Visitor<?, E> aVisitor)
        throws E
    {
        for (Object bean: aBean.getContent()) {
            if (bean instanceof Visitable) {
                ((Visitable) bean).accept(aVisitor);
            } else {
                if (bean instanceof JAXBElement<?> ) {
                    if (((JAXBElement<?> ) bean).getValue() instanceof Visitable) {
                        ((Visitable)((JAXBElement<?> ) bean).getValue()).accept(aVisitor);
                    }
                }
            }
        }
    }

    @Override
    public void traverse(TTextAnnotation aBean, Visitor<?, E> aVisitor)
        throws E
    {
        if (aBean.getText()!= null) {
            aBean.getText().accept(aVisitor);
        }
        for (TDocumentation bean: aBean.getDocumentation()) {
            bean.accept(aVisitor);
        }
        if (aBean.getExtensionElements()!= null) {
            aBean.getExtensionElements().accept(aVisitor);
        }
    }

    @Override
    public void traverse(TTimerEventDefinition aBean, Visitor<?, E> aVisitor)
        throws E
    {
        if (aBean.getTimeDate()!= null) {
            aBean.getTimeDate().accept(aVisitor);
        }
        if (aBean.getTimeDuration()!= null) {
            aBean.getTimeDuration().accept(aVisitor);
        }
        if (aBean.getTimeCycle()!= null) {
            aBean.getTimeCycle().accept(aVisitor);
        }
        for (TDocumentation bean: aBean.getDocumentation()) {
            bean.accept(aVisitor);
        }
        if (aBean.getExtensionElements()!= null) {
            aBean.getExtensionElements().accept(aVisitor);
        }
    }

    @Override
    public void traverse(TTransaction aBean, Visitor<?, E> aVisitor)
        throws E
    {
        for (TLaneSet bean: aBean.getLaneSet()) {
            bean.accept(aVisitor);
        }
        for (JAXBElement<? extends TFlowElement> obj: aBean.getFlowElement()) {
            if (obj.getValue()!= null) {
                obj.getValue().accept(aVisitor);
            }
        }
        for (JAXBElement<? extends TArtifact> obj: aBean.getArtifact()) {
            if (obj.getValue()!= null) {
                obj.getValue().accept(aVisitor);
            }
        }
        if (aBean.getIoSpecification()!= null) {
            aBean.getIoSpecification().accept(aVisitor);
        }
        for (TProperty bean: aBean.getProperty()) {
            bean.accept(aVisitor);
        }
        for (TDataInputAssociation bean: aBean.getDataInputAssociation()) {
            bean.accept(aVisitor);
        }
        for (TDataOutputAssociation bean: aBean.getDataOutputAssociation()) {
            bean.accept(aVisitor);
        }
        for (JAXBElement<? extends TResourceRole> obj: aBean.getResourceRole()) {
            if (obj.getValue()!= null) {
                obj.getValue().accept(aVisitor);
            }
        }
        if (aBean.getLoopCharacteristics()!= null) {
            aBean.getLoopCharacteristics().getValue().accept(aVisitor);
        }
        if (aBean.getDefault() instanceof Visitable) {
            ((Visitable) aBean.getDefault()).accept(aVisitor);
        }
        if (aBean.getAuditing()!= null) {
            aBean.getAuditing().accept(aVisitor);
        }
        if (aBean.getMonitoring()!= null) {
            aBean.getMonitoring().accept(aVisitor);
        }
        for (TDocumentation bean: aBean.getDocumentation()) {
            bean.accept(aVisitor);
        }
        if (aBean.getExtensionElements()!= null) {
            aBean.getExtensionElements().accept(aVisitor);
        }
    }

    @Override
    public void traverse(TUserTask aBean, Visitor<?, E> aVisitor)
        throws E
    {
        for (TRendering bean: aBean.getRendering()) {
            bean.accept(aVisitor);
        }
        if (aBean.getIoSpecification()!= null) {
            aBean.getIoSpecification().accept(aVisitor);
        }
        for (TProperty bean: aBean.getProperty()) {
            bean.accept(aVisitor);
        }
        for (TDataInputAssociation bean: aBean.getDataInputAssociation()) {
            bean.accept(aVisitor);
        }
        for (TDataOutputAssociation bean: aBean.getDataOutputAssociation()) {
            bean.accept(aVisitor);
        }
        for (JAXBElement<? extends TResourceRole> obj: aBean.getResourceRole()) {
            if (obj.getValue()!= null) {
                obj.getValue().accept(aVisitor);
            }
        }
        if (aBean.getLoopCharacteristics()!= null) {
            aBean.getLoopCharacteristics().getValue().accept(aVisitor);
        }
        if (aBean.getDefault() instanceof Visitable) {
            ((Visitable) aBean.getDefault()).accept(aVisitor);
        }
        if (aBean.getAuditing()!= null) {
            aBean.getAuditing().accept(aVisitor);
        }
        if (aBean.getMonitoring()!= null) {
            aBean.getMonitoring().accept(aVisitor);
        }
        for (TDocumentation bean: aBean.getDocumentation()) {
            bean.accept(aVisitor);
        }
        if (aBean.getExtensionElements()!= null) {
            aBean.getExtensionElements().accept(aVisitor);
        }
    }

}
