//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.06 at 05:11:55 PM BRT 
//


package org.submarine.client.bpmn;

import javax.annotation.Generated;

@Generated("Generated by jaxb-visitor")
public interface TraversingVisitorProgressMonitor {


    void visited(Object aVisitable);

    void traversed(Object aVisitable);

}
